language: python
python:
    - "2.7"

addons:
    apt:
        packages:
            - python-dev
            - libpq-dev
            - libxml2-dev
            - libxslt1-dev
            - redis-server

before_install:
      - wget https://dl.influxdata.com/influxdb/releases/influxdb_1.0.2_amd64.deb
      - sudo dpkg -i influxdb_1.0.2_amd64.deb
      - wget https://dl.influxdata.com/kapacitor/releases/kapacitor_1.0.2_amd64.deb
      - sudo dpkg -i kapacitor_1.0.2_amd64.deb
      - sudo /etc/init.d/influxdb start
      - sleep 8
      - sudo service kapacitor start
      - sleep 8

notifications:
      slack: gledev:BDwNaKy9PDs7g7zSd5c3cMx

install:
    - pip install -r requirements.txt

before_script:
    - python manage.py migrate --noinput
script: 
    - python -W ignore manage.py -p test_repor*.py test 
