language: python
python:
    - "2.7"
addons:
    apt:
        packages:
            - python-dev
            - libpq-dev
            - libxml2-dev
            - libxslt1-dev
            - nodejs-legacy
            - redis-server
            - redis-client
before_install:
      - wget https://s3.amazonaws.com/influxdb/influxdb_0.10.1-1_amd64.deb
      - sudo dpkg -i influxdb_0.10.1-1_amd64.deb
      - sudo /etc/init.d/influxdb start
      - sleep 8

install:
    - pip install -r requirements.txt

before_script:
      - python manage.py migrate --noinput
script: 
    - python -W ignore manage.py test
