# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-03 06:13
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import geoposition.fields


class Migration(migrations.Migration):

    replaces = [(b'seshdash', '0001_initial'), (b'seshdash', '0002_auto_20151228_1447'), (b'seshdash', '0003_auto_20151228_1705'), (b'seshdash', '0004_auto_20151228_1707'), (b'seshdash', '0005_vrm_account_number_of_sites'), (b'seshdash', '0006_sesh_site_position'), (b'seshdash', '0007_auto_20160108_1020'), (b'seshdash', '0008_auto_20160113_1206'), (b'seshdash', '0009_auto_20160114_1358'), (b'seshdash', '0010_auto_20160114_1443'), (b'seshdash', '0011_sesh_alert_trigger_alert'), (b'seshdash', '0012_auto_20160310_1115'), (b'seshdash', '0013_auto_20160310_1122'), (b'seshdash', '0014_auto_20160310_1158'), (b'seshdash', '0015_remove_sesh_alert_trigger_alert'), (b'seshdash', '0016_sesh_alert_trigger_alert'), (b'seshdash', '0017_auto_20160311_1228'), (b'seshdash', '0018_auto_20160316_1647'), (b'seshdash', '0019_auto_20160317_1440'), (b'seshdash', '0020_auto_20160317_1519'), (b'seshdash', '0021_auto_20160320_1858'), (b'seshdash', '0022_auto_20160321_0926'), (b'seshdash', '0023_auto_20160321_1350'), (b'seshdash', '0024_auto_20160328_1110'), (b'seshdash', '0025_auto_20160328_1159'), (b'seshdash', '0026_auto_20160328_1334'), (b'seshdash', '0027_auto_20160328_1448'), (b'seshdash', '0028_auto_20160328_1646'), (b'seshdash', '0029_auto_20160329_1433'), (b'seshdash', '0030_auto_20160329_1445'), (b'seshdash', '0031_auto_20160329_1521'), (b'seshdash', '0032_auto_20160329_1629'), (b'seshdash', '0033_auto_20160331_1131'), (b'seshdash', '0034_auto_20160331_1324'), (b'seshdash', '0035_auto_20160331_1501'), (b'seshdash', '0036_auto_20160331_1556'), (b'seshdash', '0037_auto_20160331_1641'), (b'seshdash', '0038_auto_20160401_1340'), (b'seshdash', '0039_auto_20160401_1411'), (b'seshdash', '0040_auto_20160401_1452'), (b'seshdash', '0041_auto_20160401_2135'), (b'seshdash', '0042_auto_20160404_1408'), (b'seshdash', '0043_auto_20160404_1420'), (b'seshdash', '0044_auto_20160404_1457'), (b'seshdash', '0024_auto_20160404_0953'), (b'seshdash', '0025_auto_20160404_1214'), (b'seshdash', '0026_auto_20160404_1215'), (b'seshdash', '0027_auto_20160404_1637'), (b'seshdash', '0028_auto_20160411_1055'), (b'seshdash', '0045_merge'), (b'seshdash', '0046_auto_20160411_1358'), (b'seshdash', '0047_auto_20160411_1358'), (b'seshdash', '0048_auto_20160411_1358'), (b'seshdash', '0049_auto_20160411_1358'), (b'seshdash', '0050_auto_20160412_1431'), (b'seshdash', '0051_auto_20160412_1449'), (b'seshdash', '0052_auto_20160418_1339'), (b'seshdash', '0053_auto_20160418_1640'), (b'seshdash', '0054_auto_20160418_1656'), (b'seshdash', '0052_auto_20160415_1524'), (b'seshdash', '0053_auto_20160419_1334'), (b'seshdash', '0045_auto_20160406_1500'), (b'seshdash', '0046_auto_20160421_0916'), (b'seshdash', '0055_merge'), (b'seshdash', '0056_auto_20160421_1110'), (b'seshdash', '0057_auto_20160421_1527'), (b'seshdash', '0058_auto_20160421_1755'), (b'seshdash', '0059_auto_20160422_1202'), (b'seshdash', '0052_auto_20160415_1110'), (b'seshdash', '0060_merge'), (b'seshdash', '0061_auto_20160425_1459'), (b'seshdash', '0062_auto_20160426_1118'), (b'seshdash', '0061_auto_20160422_1829'), (b'seshdash', '0062_auto_20160422_1841'), (b'seshdash', '0063_merge'), (b'seshdash', '0064_auto_20160426_1159'), (b'seshdash', '0065_auto_20160426_1159'), (b'seshdash', '0063_auto_20160428_1053'), (b'seshdash', '0066_merge'), (b'seshdash', '0067_auto_20160504_1004'), (b'seshdash', '0063_auto_20160430_1113'), (b'seshdash', '0064_auto_20160430_1744'), (b'seshdash', '0068_merge'), (b'seshdash', '0061_auto_20160425_1348'), (b'seshdash', '0062_auto_20160425_1446'), (b'seshdash', '0063_auto_20160425_1457'), (b'seshdash', '0067_merge'), (b'seshdash', '0068_auto_20160504_1247'), (b'seshdash', '0069_merge'), (b'seshdash', '0070_auto_20160505_1159'), (b'seshdash', '0067_auto_20160504_1326'), (b'seshdash', '0071_merge'), (b'seshdash', '0066_auto_20160504_0958'), (b'seshdash', '0067_auto_20160504_1222'), (b'seshdash', '0068_auto_20160505_1156'), (b'seshdash', '0072_merge'), (b'seshdash', '0073_auto_20160509_1743'), (b'seshdash', '0074_auto_20160512_1529'), (b'seshdash', '0075_auto_20160513_1330'), (b'seshdash', '0075_auto_20160513_1308'), (b'seshdash', '0076_merge'), (b'seshdash', '0077_auto_20160516_1200'), (b'seshdash', '0078_auto_20160516_1200'), (b'seshdash', '0079_auto_20160516_1407'), (b'seshdash', '0080_auto_20160516_1423'), (b'seshdash', '0081_auto_20160516_1503'), (b'seshdash', '0082_auto_20160516_1605'), (b'seshdash', '0083_auto_20160523_1100'), (b'seshdash', '0084_auto_20160523_1114'), (b'seshdash', '0072_auto_20160510_1318'), (b'seshdash', '0074_merge'), (b'seshdash', '0075_auto_20160518_0931'), (b'seshdash', '0083_merge'), (b'seshdash', '0085_merge'), (b'seshdash', '0086_auto_20160531_1328'), (b'seshdash', '0087_auto_20160601_1022'), (b'seshdash', '0088_auto_20160601_1024'), (b'seshdash', '0089_auto_20160601_1028'), (b'seshdash', '0090_auto_20160601_1041'), (b'seshdash', '0091_auto_20160601_1044'), (b'seshdash', '0086_auto_20160528_1712'), (b'seshdash', '0092_merge'), (b'seshdash', '0087_auto_20160601_1159'), (b'seshdash', '0088_auto_20160601_1200'), (b'seshdash', '0089_auto_20160601_1417'), (b'seshdash', '0090_auto_20160601_1518'), (b'seshdash', '0093_merge')]

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert_Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_field', models.CharField(choices=[(b'battery_voltage', b'battery voltage'), (b'soc', b'System State of Charge'), (b'AC_output', b'AC Loads'), (b'pv_production', b'Solar Energy Produced'), (b'main_on', b'Grid Availible'), (b'genset_state', b'Generator on')], max_length=100)),
                ('value', models.FloatField()),
                ('operator', models.CharField(choices=[(b'eq', b'equals'), (b'lt', b'less than'), (b'gt', b'greater than')], default=b'lt', max_length=2)),
                ('send_mail', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'System Alert Rule',
                'verbose_name_plural': 'System Alert Rules',
            },
        ),
        migrations.CreateModel(
            name='BoM_Data_Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('soc', models.FloatField()),
                ('battery_voltage', models.FloatField()),
                ('AC_Voltage_in', models.FloatField(default=0)),
                ('AC_Voltage_out', models.FloatField(default=0)),
                ('AC_input', models.FloatField()),
                ('AC_output', models.FloatField()),
                ('AC_Load_in', models.FloatField()),
                ('AC_Load_out', models.FloatField()),
                ('pv_production', models.FloatField(default=0)),
                ('inverter_state', models.CharField(max_length=100)),
                ('main_on', models.BooleanField(default=False)),
                ('genset_state', models.CharField(max_length=100)),
                ('relay_state', models.CharField(max_length=100)),
                ('trans', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Data Point',
            },
        ),
        migrations.CreateModel(
            name='Daily_Data_Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_pv_yield', models.FloatField(default=0)),
                ('daily_power_consumption', models.FloatField(default=0)),
                ('daily_battery_charge', models.FloatField(default=0)),
                ('date', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Daily Aggregate Data Point',
            },
        ),
        migrations.CreateModel(
            name='Sesh_Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('isSilence', models.BooleanField()),
                ('alertSent', models.BooleanField()),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seshdash.Alert_Rule')),
            ],
            options={
                'verbose_name': 'System Alert',
                'verbose_name_plural': 'System Alerts',
            },
        ),
        migrations.CreateModel(
            name='SESH_RMC_Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('API_KEY', models.CharField(default=b'', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sesh_Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=100)),
                ('comission_date', models.DateTimeField(verbose_name=b'date comissioned')),
                ('location_city', models.CharField(max_length=100)),
                ('location_country', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('installed_kw', models.FloatField()),
                ('number_of_pv_strings', models.IntegerField()),
                ('Number_of_panels', models.IntegerField()),
                ('battery_bank_capacity', models.IntegerField()),
                ('has_genset', models.BooleanField()),
                ('has_grid', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Sesh Site',
                'verbose_name_plural': 'Sesh Sites',
                'permissions': (('view_Sesh_Site', 'View Sesh Site'),),
            },
        ),
        migrations.CreateModel(
            name='Sesh_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seshuser', to=settings.AUTH_USER_MODEL)),
                ('phone_number', models.CharField(blank=True, max_length=12, null=True)),
                ('on_call', models.BooleanField(default=False)),
                ('send_mail', models.BooleanField(default=False)),
                ('send_sms', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Site_Weather_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(unique_for_date=True, verbose_name=b'date')),
                ('temp', models.IntegerField()),
                ('condition', models.CharField(max_length=20)),
                ('cloud_cover', models.FloatField()),
                ('sunrise', models.TimeField()),
                ('sunset', models.TimeField()),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seshdash.Sesh_Site')),
            ],
            options={
                'verbose_name': 'Weather Data',
            },
        ),
        migrations.CreateModel(
            name='Trend_Data_Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pv_yield', models.FloatField(default=0)),
                ('battery_usage', models.FloatField(default=0)),
                ('system_efficiency', models.FloatField(default=0)),
                ('system_capacity', models.FloatField(default=0)),
                ('battery_efficieny', models.FloatField(default=0)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seshdash.Sesh_Site')),
            ],
        ),
        migrations.CreateModel(
            name='VRM_Account',
            fields=[
                ('vrm_user_id', models.CharField(default=b'', max_length=100, primary_key=True, serialize=False)),
                ('vrm_password', models.CharField(default=b'', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='sesh_site',
            name='vrm_account',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='seshdash.VRM_Account'),
        ),
        migrations.AddField(
            model_name='sesh_alert',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seshdash.Sesh_Site'),
        ),
        migrations.AddField(
            model_name='daily_data_point',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seshdash.Sesh_Site'),
        ),
        migrations.AddField(
            model_name='bom_data_point',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seshdash.Sesh_Site'),
        ),
        migrations.AddField(
            model_name='alert_rule',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seshdash.Sesh_Site'),
        ),
        migrations.AlterUniqueTogether(
            name='site_weather_data',
            unique_together=set([('site', 'date')]),
        ),
        migrations.RenameField(
            model_name='daily_data_point',
            old_name='daily_power_consumption',
            new_name='daily_power_consumption_total',
        ),
        migrations.AddField(
            model_name='daily_data_point',
            name='daily_grid_outage_t',
            field=models.FloatField(default=0, verbose_name=b'Grid outage t'),
        ),
        migrations.AddField(
            model_name='daily_data_point',
            name='daily_grid_usage',
            field=models.FloatField(default=0, verbose_name=b'Grid usage'),
        ),
        migrations.AddField(
            model_name='daily_data_point',
            name='daily_no_of_alerts',
            field=models.IntegerField(default=0, verbose_name=b'Number of alerts'),
        ),
        migrations.AddField(
            model_name='daily_data_point',
            name='daily_power_cons_pv',
            field=models.FloatField(default=0, verbose_name=b'Power consumption pv'),
        ),
        migrations.AddField(
            model_name='daily_data_point',
            name='daily_grid_outage_n',
            field=models.FloatField(default=0, verbose_name=b'Grid outagen n'),
        ),
        migrations.AlterField(
            model_name='daily_data_point',
            name='daily_battery_charge',
            field=models.FloatField(default=0, verbose_name=b'Battery Charge'),
        ),
        migrations.AlterField(
            model_name='daily_data_point',
            name='daily_power_consumption_total',
            field=models.FloatField(default=0, verbose_name=b'Daily Power Consumption'),
        ),
        migrations.AlterField(
            model_name='daily_data_point',
            name='daily_pv_yield',
            field=models.FloatField(default=0, verbose_name=b'Battery Voltage'),
        ),
        migrations.AlterUniqueTogether(
            name='daily_data_point',
            unique_together=set([('site', 'date')]),
        ),
        migrations.AddField(
            model_name='bom_data_point',
            name='AC_output_absolute',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='bom_data_point',
            name='AC_Load_in',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='bom_data_point',
            name='AC_Load_out',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='bom_data_point',
            name='AC_input',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='bom_data_point',
            name='AC_output',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='bom_data_point',
            name='battery_voltage',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='bom_data_point',
            name='genset_state',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bom_data_point',
            name='relay_state',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bom_data_point',
            name='soc',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='bom_data_point',
            name='target_alert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seshdash.Sesh_Alert'),
        ),
        migrations.AlterField(
            model_name='bom_data_point',
            name='inverter_state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bom_data_point',
            name='inverter_state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='bom_data_point',
            unique_together=set([('site', 'time')]),
        ),
        migrations.AddField(
            model_name='sesh_site',
            name='vrm_site_id',
            field=models.CharField(blank=True, default=b'', max_length=20, null=True),
        ),
        migrations.AlterModelOptions(
            name='vrm_account',
            options={'verbose_name': 'VRM Account'},
        ),
        migrations.AddField(
            model_name='vrm_account',
            name='number_of_sites',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sesh_site',
            name='position',
            field=geoposition.fields.GeopositionField(blank=True, max_length=42),
        ),
        migrations.RemoveField(
            model_name='sesh_site',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='sesh_site',
            name='longitude',
        ),
        migrations.CreateModel(
            name='RMC_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(default=None)),
                ('signal_strength', models.IntegerField(default=None)),
                ('data_sent_24h', models.IntegerField(default=None)),
                ('rmc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seshdash.Sesh_RMC_Account')),
                ('minutes_last_contact', models.IntegerField(default=None)),
                ('time', models.DateTimeField(default=datetime.datetime(2016, 3, 31, 11, 24, 49, 869894, tzinfo=utc))),
            ],
        ),
        migrations.AddField(
            model_name='sesh_site',
            name='rmc_account',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='seshdash.SESH_RMC_Account'),
        ),
        migrations.AlterModelOptions(
            name='sesh_site',
            options={},
        ),
        migrations.RemoveField(
            model_name='sesh_site',
            name='rmc_account',
        ),
        migrations.AlterField(
            model_name='sesh_rmc_account',
            name='API_KEY',
            field=models.CharField(default=b'', max_length=130),
        ),
        migrations.AlterModelOptions(
            name='sesh_site',
            options={'permissions': (('view_Sesh_Site', 'View Sesh Site'),), 'verbose_name': 'Sesh Site', 'verbose_name_plural': 'Sesh Sites'},
        ),
        migrations.RenameField(
            model_name='sesh_site',
            old_name='number_of_pv_strings',
            new_name='system_voltage',
        ),
        migrations.AlterModelOptions(
            name='sesh_rmc_account',
            options={'verbose_name': 'RMC API Account'},
        ),
        migrations.RenameField(
            model_name='sesh_site',
            old_name='Number_of_panels',
            new_name='number_of_panels',
        ),
        migrations.AddField(
            model_name='sesh_alert',
            name='emailSent',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sesh_alert',
            name='slackSent',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sesh_alert',
            name='smsSent',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='sesh_alert',
            name='alertSent',
        ),
        migrations.AlterField(
            model_name='alert_rule',
            name='check_field',
            field=models.CharField(choices=[(b'battery_voltage', b'battery voltage'), (b'soc', b'System State of Charge'), (b'AC_output', b'AC Loads'), (b'pv_production', b'Solar Energy Produced'), (b'main_on', b'Grid Availible'), (b'genset_state', b'Generator on'), (b'model#field_name', b'Model FieldName'), (b'RMC_status#last_contact', b'RMC Last Contact')], max_length=100),
        ),
        migrations.AlterField(
            model_name='alert_rule',
            name='check_field',
            field=models.CharField(choices=[(b'battery_voltage', b'battery voltage'), (b'soc', b'System State of Charge'), (b'AC_output', b'AC Loads'), (b'pv_production', b'Solar Energy Produced'), (b'main_on', b'Grid Availible'), (b'genset_state', b'Generator on'), (b'model#field_name', b'Model FieldName'), (b'RMC_status#minutes_last_contact', b'RMC Last Contact')], max_length=100),
        ),
        migrations.AlterField(
            model_name='alert_rule',
            name='check_field',
            field=models.CharField(choices=[(b'BoM_Data_Point#battery_voltage', b'battery voltage'), (b'BoM_Data_Point#soc', b'System State of Charge'), (b'BoM_Data_Point#AC_output', b'AC Loads'), (b'BoM_Data_Point#pv_production', b'Solar Energy Produced'), (b'BoM_Data_Point#main_on', b'Grid Availible'), (b'BoM_Data_Point#genset_state', b'Generator on'), (b'RMC_status#minutes_last_contact', b'RMC Last Contact')], max_length=100),
        ),
        migrations.AddField(
            model_name='rmc_status',
            name='target_alert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seshdash.Sesh_Alert'),
        ),
        migrations.AlterField(
            model_name='rmc_status',
            name='rmc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seshdash.Sesh_RMC_Account'),
        ),
        migrations.AlterField(
            model_name='rmc_status',
            name='rmc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seshdash.Sesh_RMC_Account'),
        ),
        migrations.AlterField(
            model_name='rmc_status',
            name='rmc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seshdash.Sesh_RMC_Account'),
        ),
        migrations.AlterField(
            model_name='rmc_status',
            name='rmc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seshdash.Sesh_RMC_Account'),
        ),
        migrations.AlterField(
            model_name='rmc_status',
            name='rmc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seshdash.Sesh_RMC_Account'),
        ),
        migrations.AddField(
            model_name='sesh_alert',
            name='point_model',
            field=models.CharField(default=b'BoM_Data_Point', max_length=40),
        ),
        migrations.AlterField(
            model_name='rmc_status',
            name='rmc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seshdash.Sesh_RMC_Account'),
        ),
        migrations.AlterModelOptions(
            name='sesh_alert',
            options={},
        ),
        migrations.AlterField(
            model_name='rmc_status',
            name='rmc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seshdash.Sesh_RMC_Account'),
        ),
        migrations.AlterField(
            model_name='rmc_status',
            name='rmc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seshdash.Sesh_RMC_Account'),
        ),
        migrations.AlterField(
            model_name='rmc_status',
            name='rmc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seshdash.Sesh_RMC_Account'),
        ),
        migrations.AlterField(
            model_name='rmc_status',
            name='rmc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seshdash.Sesh_RMC_Account'),
        ),
        migrations.AlterModelOptions(
            name='sesh_rmc_account',
            options={'verbose_name': 'RMC API Account'},
        ),
        migrations.AddField(
            model_name='sesh_site',
            name='import_data',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rmc_status',
            name='rmc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seshdash.Sesh_RMC_Account'),
        ),
        migrations.AlterField(
            model_name='rmc_status',
            name='rmc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seshdash.Sesh_RMC_Account'),
        ),
        migrations.AlterField(
            model_name='rmc_status',
            name='rmc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seshdash.Sesh_RMC_Account'),
        ),
        migrations.AlterField(
            model_name='rmc_status',
            name='rmc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seshdash.Sesh_RMC_Account'),
        ),
        migrations.AlterField(
            model_name='rmc_status',
            name='rmc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seshdash.Sesh_RMC_Account'),
        ),
        migrations.AlterField(
            model_name='sesh_site',
            name='has_genset',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sesh_site',
            name='has_grid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rmc_status',
            name='rmc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seshdash.Sesh_RMC_Account'),
        ),
        migrations.AlterField(
            model_name='rmc_status',
            name='rmc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seshdash.Sesh_RMC_Account'),
        ),
        migrations.AlterField(
            model_name='rmc_status',
            name='rmc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seshdash.Sesh_RMC_Account'),
        ),
        migrations.AlterField(
            model_name='rmc_status',
            name='rmc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seshdash.Sesh_RMC_Account'),
        ),
        migrations.RenameField(
            model_name='sesh_rmc_account',
            old_name='API_KEY',
            new_name='api_key',
        ),
        migrations.AddField(
            model_name='sesh_rmc_account',
            name='api_key_numeric',
            field=models.CharField(default=b'', max_length=130),
        ),
        migrations.AlterField(
            model_name='rmc_status',
            name='rmc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seshdash.Sesh_RMC_Account'),
        ),
        migrations.AlterField(
            model_name='rmc_status',
            name='rmc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seshdash.Sesh_RMC_Account'),
        ),
        migrations.AlterField(
            model_name='rmc_status',
            name='rmc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seshdash.Sesh_RMC_Account'),
        ),
        migrations.AlterField(
            model_name='sesh_site',
            name='position',
            field=geoposition.fields.GeopositionField(max_length=42),
        ),
        migrations.AlterModelOptions(
            name='rmc_status',
            options={'verbose_name': 'System Alert', 'verbose_name_plural': 'System Alerts'},
        ),
        migrations.AlterModelOptions(
            name='sesh_alert',
            options={'verbose_name': 'System Alert', 'verbose_name_plural': 'System Alerts'},
        ),
        migrations.AddField(
            model_name='rmc_status',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seshdash.Sesh_Site'),
        ),
        migrations.AlterField(
            model_name='rmc_status',
            name='rmc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seshdash.Sesh_RMC_Account'),
        ),
        migrations.AlterField(
            model_name='rmc_status',
            name='data_sent_24h',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='rmc_status',
            name='ip_address',
            field=models.GenericIPAddressField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='rmc_status',
            name='rmc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seshdash.Sesh_RMC_Account'),
        ),
        migrations.AlterField(
            model_name='rmc_status',
            name='signal_strength',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='rmc_status',
            name='rmc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seshdash.Sesh_RMC_Account'),
        ),
        migrations.AlterField(
            model_name='rmc_status',
            name='rmc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seshdash.Sesh_RMC_Account'),
        ),
        migrations.AlterField(
            model_name='rmc_status',
            name='rmc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seshdash.Sesh_RMC_Account'),
        ),
        migrations.AlterField(
            model_name='rmc_status',
            name='rmc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seshdash.Sesh_RMC_Account'),
        ),
        migrations.AlterField(
            model_name='rmc_status',
            name='rmc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seshdash.Sesh_RMC_Account'),
        ),
        migrations.AlterModelOptions(
            name='rmc_status',
            options={'verbose_name': 'RMC Status', 'verbose_name_plural': "RMC Status's"},
        ),
        migrations.AlterField(
            model_name='rmc_status',
            name='rmc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seshdash.Sesh_RMC_Account'),
        ),
        migrations.AlterField(
            model_name='rmc_status',
            name='rmc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seshdash.Sesh_RMC_Account'),
        ),
        migrations.AlterField(
            model_name='rmc_status',
            name='rmc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seshdash.Sesh_RMC_Account'),
        ),
        migrations.AlterField(
            model_name='rmc_status',
            name='rmc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seshdash.Sesh_RMC_Account'),
        ),
        migrations.AlterField(
            model_name='rmc_status',
            name='rmc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seshdash.Sesh_RMC_Account'),
        ),
        migrations.AlterField(
            model_name='rmc_status',
            name='rmc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seshdash.Sesh_RMC_Account'),
        ),
        migrations.AlterField(
            model_name='rmc_status',
            name='rmc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seshdash.Sesh_RMC_Account'),
        ),
        migrations.AlterField(
            model_name='rmc_status',
            name='rmc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seshdash.Sesh_RMC_Account'),
        ),
        migrations.AlterField(
            model_name='rmc_status',
            name='rmc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seshdash.Sesh_RMC_Account'),
        ),
        migrations.AlterField(
            model_name='rmc_status',
            name='rmc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seshdash.Sesh_RMC_Account'),
        ),
        migrations.AlterField(
            model_name='rmc_status',
            name='rmc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seshdash.Sesh_RMC_Account'),
        ),
        migrations.AlterField(
            model_name='rmc_status',
            name='rmc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seshdash.Sesh_RMC_Account'),
        ),
        migrations.AlterField(
            model_name='rmc_status',
            name='rmc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seshdash.Sesh_RMC_Account'),
        ),
        migrations.AlterField(
            model_name='rmc_status',
            name='rmc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seshdash.Sesh_RMC_Account'),
        ),
        migrations.AlterField(
            model_name='rmc_status',
            name='rmc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seshdash.Sesh_RMC_Account'),
        ),
        migrations.AlterField(
            model_name='rmc_status',
            name='rmc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seshdash.Sesh_RMC_Account'),
        ),
        migrations.AlterField(
            model_name='rmc_status',
            name='rmc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seshdash.Sesh_RMC_Account'),
        ),
        migrations.AlterField(
            model_name='rmc_status',
            name='rmc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seshdash.Sesh_RMC_Account'),
        ),
        migrations.AlterField(
            model_name='rmc_status',
            name='rmc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seshdash.Sesh_RMC_Account'),
        ),
        migrations.AddField(
            model_name='sesh_site',
            name='time_zone',
            field=models.CharField(default=b'Africa/Kigali', max_length=100),
        ),
        migrations.AlterField(
            model_name='rmc_status',
            name='rmc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seshdash.Sesh_RMC_Account'),
        ),
        migrations.AddField(
            model_name='sesh_alert',
            name='point_id',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='alert_rule',
            name='check_field',
            field=models.CharField(choices=[(b'BoM_Data_Point#battery_voltage', b'battery voltage'), (b'BoM_Data_Point#soc', b'System State of Charge'), (b'BoM_Data_Point#AC_output', b'AC Loads'), (b'BoM_Data_Point#pv_production', b'Solar Energy Produced'), (b'BoM_Data_Point#main_on', b'Grid Availible'), (b'BoM_Data_Point#genset_state', b'Generator on'), (b'RMC_status#minutes_last_contact', b'RMC Last Contact'), (b'battery_voltage', b'Battery Voltage in influx rule')], max_length=100),
        ),
        migrations.AlterField(
            model_name='rmc_status',
            name='rmc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seshdash.Sesh_RMC_Account'),
        ),
        migrations.AlterField(
            model_name='rmc_status',
            name='rmc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seshdash.Sesh_RMC_Account'),
        ),
        migrations.AlterField(
            model_name='rmc_status',
            name='rmc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seshdash.Sesh_RMC_Account'),
        ),
        migrations.AlterField(
            model_name='rmc_status',
            name='rmc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seshdash.Sesh_RMC_Account'),
        ),
        migrations.AlterField(
            model_name='rmc_status',
            name='rmc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seshdash.Sesh_RMC_Account'),
        ),
        migrations.AlterField(
            model_name='sesh_alert',
            name='alert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_point', to='seshdash.Alert_Rule'),
        ),
        migrations.AlterField(
            model_name='rmc_status',
            name='rmc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seshdash.Sesh_RMC_Account'),
        ),
        migrations.AlterField(
            model_name='rmc_status',
            name='rmc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seshdash.Sesh_RMC_Account'),
        ),
        migrations.AlterField(
            model_name='rmc_status',
            name='rmc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seshdash.Sesh_RMC_Account'),
        ),
        migrations.AlterField(
            model_name='rmc_status',
            name='rmc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seshdash.Sesh_RMC_Account'),
        ),
        migrations.CreateModel(
            name='Sesh_Organisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slack_token', models.CharField(max_length=100)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
            ],
        ),
        migrations.AlterField(
            model_name='rmc_status',
            name='rmc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seshdash.Sesh_RMC_Account'),
        ),
        migrations.AlterField(
            model_name='rmc_status',
            name='rmc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seshdash.Sesh_RMC_Account'),
        ),
        migrations.AlterField(
            model_name='rmc_status',
            name='rmc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seshdash.Sesh_RMC_Account'),
        ),
        migrations.CreateModel(
            name='Slack_Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('is_alert_channel', models.BooleanField(default=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slack_channel', to='seshdash.Sesh_Organisation')),
            ],
        ),
        migrations.AlterField(
            model_name='rmc_status',
            name='rmc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seshdash.Sesh_RMC_Account'),
        ),
        migrations.RemoveField(
            model_name='alert_rule',
            name='send_mail',
        ),
        migrations.AlterField(
            model_name='rmc_status',
            name='rmc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seshdash.Sesh_RMC_Account'),
        ),
        migrations.AddField(
            model_name='sesh_organisation',
            name='send_slack',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rmc_status',
            name='rmc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seshdash.Sesh_RMC_Account'),
        ),
        migrations.AlterField(
            model_name='rmc_status',
            name='rmc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seshdash.Sesh_RMC_Account'),
        ),
        migrations.AlterField(
            model_name='rmc_status',
            name='rmc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seshdash.Sesh_RMC_Account'),
        ),
        migrations.CreateModel(
            name='Status_Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row1', models.CharField(choices=[(b'AC_Load_in', b'AC Load in'), (b'AC_Load_out', b'AC Load out'), (b'AC_Voltage_in', b'AC Voltage in'), (b'AC_Voltage_out', b'AC Voltage out'), (b'AC_input', b'AC input'), (b'AC_output', b'AC output'), (b'AC_output_absolute', b'AC output absolute'), (b'battery_voltage', b'Battery Voltage'), (b'genset_state', b'Genset state'), (b'main_on', b'Main on'), (b'pv_production', b'PV production'), (b'relay_state', b'Relay state'), (b'soc', b'State of Charge'), (b'trans', b'Trans')], default=b'soc', max_length=30)),
                ('row2', models.CharField(choices=[(b'AC_Load_in', b'AC Load in'), (b'AC_Load_out', b'AC Load out'), (b'AC_Voltage_in', b'AC Voltage in'), (b'AC_Voltage_out', b'AC Voltage out'), (b'AC_input', b'AC input'), (b'AC_output', b'AC output'), (b'AC_output_absolute', b'AC output absolute'), (b'battery_voltage', b'Battery Voltage'), (b'genset_state', b'Genset state'), (b'main_on', b'Main on'), (b'pv_production', b'PV production'), (b'relay_state', b'Relay state'), (b'soc', b'State of Charge'), (b'trans', b'Trans')], default=b'battery_voltage', max_length=30)),
                ('row3', models.CharField(choices=[(b'AC_Load_in', b'AC Load in'), (b'AC_Load_out', b'AC Load out'), (b'AC_Voltage_in', b'AC Voltage in'), (b'AC_Voltage_out', b'AC Voltage out'), (b'AC_input', b'AC input'), (b'AC_output', b'AC output'), (b'AC_output_absolute', b'AC output absolute'), (b'battery_voltage', b'Battery Voltage'), (b'genset_state', b'Genset state'), (b'main_on', b'Main on'), (b'pv_production', b'PV production'), (b'relay_state', b'Relay state'), (b'soc', b'State of Charge'), (b'trans', b'Trans')], default=b'AC_output_absolute', max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='rmc_status',
            name='rmc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seshdash.Sesh_RMC_Account'),
        ),
        migrations.AddField(
            model_name='sesh_site',
            name='status_card',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='seshdash.Status_Card'),
        ),
        migrations.AlterField(
            model_name='rmc_status',
            name='rmc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seshdash.Sesh_RMC_Account'),
        ),
        migrations.AlterField(
            model_name='rmc_status',
            name='rmc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seshdash.Sesh_RMC_Account'),
        ),
        migrations.AlterField(
            model_name='rmc_status',
            name='rmc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seshdash.Sesh_RMC_Account'),
        ),
        migrations.AlterField(
            model_name='rmc_status',
            name='rmc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seshdash.Sesh_RMC_Account'),
        ),
        migrations.AlterField(
            model_name='rmc_status',
            name='rmc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seshdash.Sesh_RMC_Account'),
        ),
        migrations.RemoveField(
            model_name='sesh_rmc_account',
            name='id',
        ),
        migrations.AddField(
            model_name='sesh_rmc_account',
            name='site',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='seshdash.Sesh_Site'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rmc_status',
            name='rmc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seshdash.Sesh_RMC_Account'),
        ),
        migrations.AlterField(
            model_name='rmc_status',
            name='rmc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seshdash.Sesh_RMC_Account'),
        ),
        migrations.AlterField(
            model_name='rmc_status',
            name='rmc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seshdash.Sesh_RMC_Account'),
        ),
        migrations.AlterField(
            model_name='rmc_status',
            name='rmc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seshdash.Sesh_RMC_Account'),
        ),
        migrations.AlterField(
            model_name='rmc_status',
            name='rmc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seshdash.Sesh_RMC_Account'),
        ),
    ]
