# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-05 12:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import geoposition.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert_Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_field', models.CharField(choices=[(b'BoM_Data_Point#battery_voltage', b'battery voltage'), (b'BoM_Data_Point#soc', b'System State of Charge'), (b'BoM_Data_Point#AC_output', b'AC Loads'), (b'BoM_Data_Point#pv_production', b'Solar Energy Produced'), (b'BoM_Data_Point#main_on', b'Grid Availible'), (b'BoM_Data_Point#genset_state', b'Generator on'), (b'RMC_status#minutes_last_contact', b'RMC Last Contact'), (b'battery_voltage', b'Battery Voltage in influx rule')], max_length=100)),
                ('value', models.FloatField()),
                ('operator', models.CharField(choices=[(b'eq', b'equals'), (b'lt', b'less than'), (b'gt', b'greater than')], default=b'lt', max_length=2)),
            ],
            options={
                'verbose_name': 'System Alert Rule',
                'verbose_name_plural': 'System Alert Rules',
            },
        ),
        migrations.CreateModel(
            name='BoM_Data_Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('soc', models.FloatField(default=0)),
                ('battery_voltage', models.FloatField(default=0)),
                ('AC_Voltage_in', models.FloatField(default=0)),
                ('AC_Voltage_out', models.FloatField(default=0)),
                ('AC_input', models.FloatField(default=0)),
                ('AC_output', models.FloatField(default=0)),
                ('AC_output_absolute', models.FloatField(default=0)),
                ('AC_Load_in', models.FloatField(default=0)),
                ('AC_Load_out', models.FloatField(default=0)),
                ('pv_production', models.FloatField(default=0)),
                ('inverter_state', models.CharField(blank=True, max_length=100, null=True)),
                ('main_on', models.BooleanField(default=False)),
                ('genset_state', models.IntegerField(default=0)),
                ('relay_state', models.IntegerField(default=0)),
                ('trans', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Data Point',
            },
        ),
        migrations.CreateModel(
            name='Daily_Data_Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_pv_yield', models.FloatField(default=0, verbose_name=b'Battery Voltage')),
                ('daily_power_consumption_total', models.FloatField(default=0, verbose_name=b'Daily Power Consumption')),
                ('daily_power_cons_pv', models.FloatField(default=0, verbose_name=b'Power consumption pv')),
                ('daily_battery_charge', models.FloatField(default=0, verbose_name=b'Battery Charge')),
                ('daily_grid_outage_t', models.FloatField(default=0, verbose_name=b'Grid outage t')),
                ('daily_grid_outage_n', models.FloatField(default=0, verbose_name=b'Grid outagen n')),
                ('daily_grid_usage', models.FloatField(default=0, verbose_name=b'Grid usage')),
                ('daily_no_of_alerts', models.IntegerField(default=0, verbose_name=b'Number of alerts')),
                ('date', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Daily Aggregate Data Point',
            },
        ),
        migrations.CreateModel(
            name='RMC_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(default=None, null=True)),
                ('minutes_last_contact', models.IntegerField(default=None)),
                ('signal_strength', models.IntegerField(default=None, null=True)),
                ('data_sent_24h', models.IntegerField(default=None, null=True)),
                ('time', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'RMC Status',
                'verbose_name_plural': "RMC Status's",
            },
        ),
        migrations.CreateModel(
            name='Sesh_Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('isSilence', models.BooleanField()),
                ('emailSent', models.BooleanField()),
                ('smsSent', models.BooleanField()),
                ('slackSent', models.BooleanField()),
                ('point_model', models.CharField(default=b'BoM_Data_Point', max_length=40)),
                ('point_id', models.CharField(max_length=40)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_point', to='seshdash.Alert_Rule')),
            ],
            options={
                'verbose_name': 'System Alert',
                'verbose_name_plural': 'System Alerts',
            },
        ),
        migrations.CreateModel(
            name='Sesh_Organisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_slack', models.BooleanField(default=False)),
                ('slack_token', models.CharField(max_length=100)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
            ],
        ),
        migrations.CreateModel(
            name='Sesh_Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=100, unique=True)),
                ('comission_date', models.DateTimeField(verbose_name=b'date comissioned')),
                ('location_city', models.CharField(max_length=100)),
                ('location_country', models.CharField(max_length=100)),
                ('time_zone', models.CharField(default=b'Africa/Kigali', max_length=100)),
                ('position', geoposition.fields.GeopositionField(max_length=42)),
                ('installed_kw', models.FloatField()),
                ('system_voltage', models.IntegerField()),
                ('number_of_panels', models.IntegerField()),
                ('import_data', models.BooleanField(default=False)),
                ('battery_bank_capacity', models.IntegerField()),
                ('has_genset', models.BooleanField(default=False)),
                ('has_grid', models.BooleanField(default=False)),
                ('vrm_site_id', models.CharField(blank=True, default=b'', max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Sesh Site',
                'verbose_name_plural': 'Sesh Sites',
                'permissions': (('view_Sesh_Site', 'View Sesh Site'),),
            },
        ),
        migrations.CreateModel(
            name='Sesh_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=12, null=True)),
                ('on_call', models.BooleanField(default=False)),
                ('send_mail', models.BooleanField(default=False)),
                ('send_sms', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seshuser', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Site_Weather_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(unique_for_date=True, verbose_name=b'date')),
                ('temp', models.IntegerField()),
                ('condition', models.CharField(max_length=20)),
                ('cloud_cover', models.FloatField()),
                ('sunrise', models.TimeField()),
                ('sunset', models.TimeField()),
            ],
            options={
                'verbose_name': 'Weather Data',
            },
        ),
        migrations.CreateModel(
            name='Slack_Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('is_alert_channel', models.BooleanField(default=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slack_channel', to='seshdash.Sesh_Organisation')),
            ],
        ),
        migrations.CreateModel(
            name='Status_Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row1', models.CharField(choices=[(b'AC_Load_in', b'AC Load in'), (b'AC_Load_out', b'AC Load out'), (b'AC_Voltage_in', b'AC Voltage in'), (b'AC_Voltage_out', b'AC Voltage out'), (b'AC_input', b'AC input'), (b'AC_output', b'AC output'), (b'AC_output_absolute', b'AC output absolute'), (b'battery_voltage', b'Battery Voltage'), (b'genset_state', b'Genset state'), (b'main_on', b'Main on'), (b'pv_production', b'PV production'), (b'relay_state', b'Relay state'), (b'soc', b'State of Charge'), (b'trans', b'Trans')], default=b'soc', max_length=30)),
                ('row2', models.CharField(choices=[(b'AC_Load_in', b'AC Load in'), (b'AC_Load_out', b'AC Load out'), (b'AC_Voltage_in', b'AC Voltage in'), (b'AC_Voltage_out', b'AC Voltage out'), (b'AC_input', b'AC input'), (b'AC_output', b'AC output'), (b'AC_output_absolute', b'AC output absolute'), (b'battery_voltage', b'Battery Voltage'), (b'genset_state', b'Genset state'), (b'main_on', b'Main on'), (b'pv_production', b'PV production'), (b'relay_state', b'Relay state'), (b'soc', b'State of Charge'), (b'trans', b'Trans')], default=b'battery_voltage', max_length=30)),
                ('row3', models.CharField(choices=[(b'AC_Load_in', b'AC Load in'), (b'AC_Load_out', b'AC Load out'), (b'AC_Voltage_in', b'AC Voltage in'), (b'AC_Voltage_out', b'AC Voltage out'), (b'AC_input', b'AC input'), (b'AC_output', b'AC output'), (b'AC_output_absolute', b'AC output absolute'), (b'battery_voltage', b'Battery Voltage'), (b'genset_state', b'Genset state'), (b'main_on', b'Main on'), (b'pv_production', b'PV production'), (b'relay_state', b'Relay state'), (b'soc', b'State of Charge'), (b'trans', b'Trans')], default=b'AC_output_absolute', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Trend_Data_Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pv_yield', models.FloatField(default=0)),
                ('battery_usage', models.FloatField(default=0)),
                ('system_efficiency', models.FloatField(default=0)),
                ('system_capacity', models.FloatField(default=0)),
                ('battery_efficieny', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='VRM_Account',
            fields=[
                ('vrm_user_id', models.CharField(default=b'', max_length=100, primary_key=True, serialize=False)),
                ('vrm_password', models.CharField(default=b'', max_length=100)),
                ('number_of_sites', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'VRM Account',
            },
        ),
        migrations.CreateModel(
            name='Sesh_RMC_Account',
            fields=[
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='seshdash.Sesh_Site')),
                ('api_key', models.CharField(default=b'', max_length=130)),
                ('api_key_numeric', models.CharField(default=b'', max_length=130)),
            ],
            options={
                'verbose_name': 'RMC API Account',
            },
        ),
        migrations.AddField(
            model_name='trend_data_point',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seshdash.Sesh_Site'),
        ),
        migrations.AddField(
            model_name='site_weather_data',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seshdash.Sesh_Site'),
        ),
        migrations.AddField(
            model_name='sesh_site',
            name='status_card',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='seshdash.Status_Card'),
        ),
        migrations.AddField(
            model_name='sesh_site',
            name='vrm_account',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='seshdash.VRM_Account'),
        ),
        migrations.AddField(
            model_name='sesh_alert',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seshdash.Sesh_Site'),
        ),
        migrations.AddField(
            model_name='rmc_status',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seshdash.Sesh_Site'),
        ),
        migrations.AddField(
            model_name='rmc_status',
            name='target_alert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seshdash.Sesh_Alert'),
        ),
        migrations.AddField(
            model_name='daily_data_point',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seshdash.Sesh_Site'),
        ),
        migrations.AddField(
            model_name='bom_data_point',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seshdash.Sesh_Site'),
        ),
        migrations.AddField(
            model_name='bom_data_point',
            name='target_alert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seshdash.Sesh_Alert'),
        ),
        migrations.AddField(
            model_name='alert_rule',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seshdash.Sesh_Site'),
        ),
        migrations.AlterUniqueTogether(
            name='site_weather_data',
            unique_together=set([('site', 'date')]),
        ),
        migrations.AlterUniqueTogether(
            name='daily_data_point',
            unique_together=set([('site', 'date')]),
        ),
        migrations.AlterUniqueTogether(
            name='bom_data_point',
            unique_together=set([('site', 'time')]),
        ),
    ]
