# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-15 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seshdash', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesh_organisation',
            name='slack_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
