# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-28 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seshdash', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vrm_account',
            name='vrm_site_id',
        ),
        migrations.AddField(
            model_name='sesh_site',
            name='vrm_site_id',
            field=models.CharField(default=b'', max_length=20),
        ),
    ]
