# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-28 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seshdash', '0002_auto_20151228_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vrm_account',
            name='id',
        ),
        migrations.AlterField(
            model_name='vrm_account',
            name='vrm_user_id',
            field=models.CharField(default=b'', max_length=100, primary_key=True, serialize=False),
        ),
    ]
