# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-08 08:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seshdash', '0003_auto_20160708_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesh_site',
            name='site_measurements',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='seshdash.Site_Measurements'),
        ),
    ]
