# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-28 15:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seshdash', '0003_auto_20151228_1705'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vrm_account',
            options={'verbose_name': 'VRM Account'},
        ),
    ]
