# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-12-21 15:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seshdash', '0003_auto_20161212_1209'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tick_Script',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_field_name', models.CharField(max_length=40)),
                ('output_field_name', models.CharField(max_length=40)),
                ('script', models.TextField()),
                ('function', models.CharField(max_length=20)),
                ('interval', models.CharField(max_length=10)),
                ('type', models.CharField(choices=[(b'stream', b'Stream'), (b'batch', b'Batch')], max_length=10)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seshdash.Sesh_Site')),
            ],
        ),
    ]
