# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-12-22 08:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seshdash', '0004_tick_script'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tick_script',
            old_name='type',
            new_name='script_type',
        ),
    ]
