# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-01-12 09:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seshdash', '0004_auto_20170111_1208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report_sent',
            name='report_date',
        ),
    ]
