# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-04 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seshdash', '0004_auto_20151228_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='vrm_account',
            name='number_of_sites',
            field=models.IntegerField(default=0),
        ),
    ]
