# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-01-17 14:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seshdash', '0005_remove_report_sent_report_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor_Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.IntegerField(choices=[(19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29)], default=0)),
                ('sensor_type', models.CharField(choices=[(b'Temperature Humidity', b'th'), (b'Power Voltage', b'tx'), (b'Ph Ethenoal', b'pe')], max_length=40)),
                ('index1', models.CharField(default=b'ac_power1', max_length=40)),
                ('index2', models.CharField(default=b'pv_production', max_length=40)),
                ('index3', models.CharField(default=b'consumption', max_length=40)),
                ('index4', models.CharField(default=b'grid_in', max_length=40)),
                ('index5', models.CharField(default=b'AC_Voltage_out', max_length=40)),
                ('index6', models.CharField(blank=True, max_length=40, null=True)),
                ('index7', models.CharField(blank=True, max_length=40, null=True)),
                ('index8', models.CharField(blank=True, max_length=40, null=True)),
                ('index9', models.CharField(blank=True, max_length=40, null=True)),
                ('index10', models.CharField(blank=True, max_length=40, null=True)),
                ('index11', models.CharField(blank=True, max_length=40, null=True)),
                ('index12', models.CharField(blank=True, max_length=40, null=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seshdash.Sesh_Site')),
            ],
        ),
        migrations.RemoveField(
            model_name='sensor_bmv',
            name='site',
        ),
        migrations.RemoveField(
            model_name='sensor_emonpi',
            name='site',
        ),
        migrations.RemoveField(
            model_name='sensor_emonth',
            name='site',
        ),
        migrations.RemoveField(
            model_name='sensor_emontx',
            name='site',
        ),
        migrations.DeleteModel(
            name='Sensor_BMV',
        ),
        migrations.DeleteModel(
            name='Sensor_EmonPi',
        ),
        migrations.DeleteModel(
            name='Sensor_EmonTh',
        ),
        migrations.DeleteModel(
            name='Sensor_EmonTx',
        ),
    ]
