# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-06 12:05
from __future__ import unicode_literals

from django.db import migrations
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('seshdash', '0005_vrm_account_number_of_sites'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesh_site',
            name='position',
            field=geoposition.fields.GeopositionField(blank=True, max_length=42),
        ),
    ]
