# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-01-19 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seshdash', '0006_auto_20170117_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor_node',
            name='sensor_type',
            field=models.CharField(choices=[(b'th', b'Temperature Humidity'), (b'tx', b'Power Voltage'), (b'pe', b'Ph Ethenoal')], max_length=40),
        ),
    ]
