# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-08 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seshdash', '0006_sesh_site_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='bom_data_point',
            name='AC_output_absolute',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='bom_data_point',
            name='AC_Load_in',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='bom_data_point',
            name='AC_Load_out',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='bom_data_point',
            name='AC_input',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='bom_data_point',
            name='AC_output',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='bom_data_point',
            name='battery_voltage',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='bom_data_point',
            name='genset_state',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bom_data_point',
            name='relay_state',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bom_data_point',
            name='soc',
            field=models.FloatField(default=0),
        ),
    ]
