# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-13 10:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seshdash', '0007_auto_20160108_1020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sesh_site',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='sesh_site',
            name='longitude',
        ),
    ]
