# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-12 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seshdash', '0007_auto_20160708_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status_Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
