# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-01-25 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seshdash', '0007_auto_20170119_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor_node',
            name='index2',
            field=models.CharField(blank=True, default=b'pv_production', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='sensor_node',
            name='index3',
            field=models.CharField(blank=True, default=b'consumption', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='sensor_node',
            name='index4',
            field=models.CharField(blank=True, default=b'grid_in', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='sensor_node',
            name='index5',
            field=models.CharField(blank=True, default=b'AC_Voltage_out', max_length=40, null=True),
        ),
    ]
