# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-12 12:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seshdash', '0007_auto_20160708_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmonTh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.CharField(max_length=40)),
                ('external_temperature', models.CharField(max_length=40)),
                ('humidity', models.CharField(max_length=40)),
                ('battery', models.CharField(max_length=40)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seshdash.Sesh_Site')),
            ],
        ),
        migrations.CreateModel(
            name='EmonTx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power1', models.CharField(max_length=40)),
                ('power2', models.CharField(max_length=40)),
                ('power3', models.CharField(max_length=40)),
                ('power4', models.CharField(max_length=40)),
                ('vrms', models.CharField(max_length=40)),
                ('temp1', models.CharField(max_length=40)),
                ('temp2', models.CharField(max_length=40)),
                ('temp3', models.CharField(max_length=40)),
                ('temp4', models.CharField(max_length=40)),
                ('temp5', models.CharField(max_length=40)),
                ('temp6', models.CharField(max_length=40)),
                ('pulse', models.CharField(max_length=40)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seshdash.Sesh_Site')),
            ],
        ),
    ]
