# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-01-26 09:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seshdash', '0005_auto_20161222_1026'),
        ('seshdash', '0008_auto_20170125_1352'),
    ]

    operations = [
    ]
