# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-14 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seshdash', '0008_auto_20160113_1206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='daily_data_point',
            old_name='daily_power_consumption',
            new_name='daily_power_consumption_total',
        ),
        migrations.AddField(
            model_name='daily_data_point',
            name='daily_grid_outage_t',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='daily_data_point',
            name='daily_grid_usage',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='daily_data_point',
            name='daily_grid_usage_n',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='daily_data_point',
            name='daily_no_of_alerts',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='daily_data_point',
            name='daily_power_cons_pv',
            field=models.FloatField(default=0),
        ),
    ]
