# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-01-30 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seshdash', '0008_auto_20170125_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor_node',
            name='index1',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='sensor_node',
            name='index2',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='sensor_node',
            name='index3',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='sensor_node',
            name='index4',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='sensor_node',
            name='index5',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
