# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-12 13:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seshdash', '0008_emonth_emontx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor_BMV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soc', models.CharField(max_length=40)),
                ('ce', models.CharField(max_length=40)),
                ('ttg', models.CharField(max_length=40)),
                ('v', models.CharField(max_length=40)),
                ('i', models.CharField(max_length=40)),
                ('relay', models.CharField(max_length=40)),
                ('alarm', models.CharField(max_length=40)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seshdash.Sesh_Site')),
            ],
        ),
        migrations.RenameModel(
            old_name='EmonTh',
            new_name='Sensor_EmonTh',
        ),
        migrations.RenameModel(
            old_name='EmonTx',
            new_name='Sensor_EmonTx',
        ),
    ]
