# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-14 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seshdash', '0009_auto_20160712_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor_bmv',
            name='alarm',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='sensor_bmv',
            name='ce',
            field=models.CharField(default=b'temp_ambient', max_length=40),
        ),
        migrations.AlterField(
            model_name='sensor_bmv',
            name='i',
            field=models.CharField(default=b'tempreature', max_length=40),
        ),
        migrations.AlterField(
            model_name='sensor_bmv',
            name='relay',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='sensor_bmv',
            name='soc',
            field=models.CharField(default=b'temp_fridge', max_length=40),
        ),
        migrations.AlterField(
            model_name='sensor_bmv',
            name='ttg',
            field=models.CharField(default=b'humidity', max_length=40),
        ),
        migrations.AlterField(
            model_name='sensor_bmv',
            name='v',
            field=models.CharField(default=b'battery_voltage', max_length=40),
        ),
        migrations.AlterField(
            model_name='sensor_emonth',
            name='external_temperature',
            field=models.CharField(default=b'battery_voltage', max_length=40),
        ),
        migrations.AlterField(
            model_name='sensor_emonth',
            name='humidity',
            field=models.CharField(default=b'battery_load', max_length=40),
        ),
        migrations.AlterField(
            model_name='sensor_emonth',
            name='temperature',
            field=models.CharField(default=b'soc', max_length=40),
        ),
        migrations.AlterField(
            model_name='sensor_emontx',
            name='power1',
            field=models.CharField(default=b'ac_power1', max_length=40),
        ),
        migrations.AlterField(
            model_name='sensor_emontx',
            name='power2',
            field=models.CharField(default=b'pv_production', max_length=40),
        ),
        migrations.AlterField(
            model_name='sensor_emontx',
            name='power3',
            field=models.CharField(default=b'consumption', max_length=40),
        ),
        migrations.AlterField(
            model_name='sensor_emontx',
            name='power4',
            field=models.CharField(default=b'grid_in', max_length=40),
        ),
        migrations.AlterField(
            model_name='sensor_emontx',
            name='pulse',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='sensor_emontx',
            name='temp1',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='sensor_emontx',
            name='temp2',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='sensor_emontx',
            name='temp3',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='sensor_emontx',
            name='temp4',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='sensor_emontx',
            name='temp5',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='sensor_emontx',
            name='temp6',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='sensor_emontx',
            name='vrms',
            field=models.CharField(default=b'AC_Voltage_out', max_length=40),
        ),
    ]
