# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-01-31 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seshdash', '0009_auto_20170130_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status_card',
            name='row1',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='status_card',
            name='row2',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='status_card',
            name='row3',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='status_card',
            name='row4',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
