# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-14 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seshdash', '0009_auto_20160114_1358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daily_data_point',
            name='daily_grid_usage_n',
        ),
        migrations.AddField(
            model_name='daily_data_point',
            name='daily_grid_outage_n',
            field=models.FloatField(default=0),
        ),
    ]
