# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-02-22 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seshdash', '0010_auto_20170131_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesh_site',
            name='has_batteries',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sesh_site',
            name='has_pv',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='alert_rule',
            name='check_field',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sesh_site',
            name='installed_kw',
            field=models.FloatField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='sesh_site',
            name='number_of_panels',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='sesh_site',
            name='system_voltage',
            field=models.IntegerField(blank=True, default=None),
        ),
    ]
