# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-19 09:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seshdash', '0008_status_rule'),
        ('seshdash', '0010_auto_20160714_1033'),
    ]

    operations = [
    ]
