# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-10 09:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seshdash', '0010_auto_20160114_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesh_alert',
            name='trigger_alert',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='seshdash.BoM_Data_Point'),
        ),
    ]
