# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-19 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seshdash', '0011_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor_bmv',
            name='node_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sensor_emonth',
            name='node_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sensor_emontx',
            name='node_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
