# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-04-05 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seshdash', '0011_auto_20170222_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='data_point',
            name='field_scale',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='data_point',
            name='field_unit',
            field=models.FloatField(choices=[(b'id', b''), (b'soc', b'%'), (b'temperature', b'C'), (b'humidity', b'%'), (b'PH', b'ph'), (b'Ethanol', b'%'), (b'battery_voltage', b'V'), (b'AC_Voltage_in', b'V'), (b'AC_Voltage_out', b'V'), (b'AC_input', b'W'), (b'AC_output', b'W'), (b'AC_Load_in', b'A'), (b'AC_Load_out', b'A'), (b'cloud_cover', b'%'), (b'pv_production', b'W'), (b'main_on', b''), (b'relay_state', b''), (b'trans', b''), (b'genset_state', b''), (b'site', b''), (b'AC_output_absolute', b'W'), (b'minutes_last_contact', b'min'), (b'daily_battery_charge', b'Wh'), (b'daily_grid_outage_n', b'minute'), (b'daily_grid_outage_t', b''), (b'daily_grid_usage', b'Wh'), (b'daily_no_of_alerts', b'alert'), (b'daily_power_cons_pv', b'W'), (b'daily_power_consumption_total', b'Wh'), (b'daily_pv_yield', b'Wh')], default=0, verbose_name=b'Data Point Name'),
        ),
    ]
