# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-05-26 06:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seshdash', '0012_auto_20170405_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='bom_data_point',
            name='battery_current',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='sensor_node',
            name='node_id',
            field=models.IntegerField(default=0),
        ),
    ]
