# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-10 09:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seshdash', '0012_auto_20160310_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesh_alert',
            name='trigger_alert',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='seshdash.BoM_Data_Point'),
        ),
    ]
