# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-19 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seshdash', '0013_auto_20160719_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor_emonth',
            name='node_id',
            field=models.IntegerField(choices=[(b'5', 5), (b'6', 6), (b'7', 7), (b'8', 8)], default=0),
        ),
        migrations.AlterField(
            model_name='sensor_emontx',
            name='node_id',
            field=models.IntegerField(choices=[(b'20', 20), (b'21', 21), (b'22', 22)], default=0),
        ),
    ]
