# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-22 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seshdash', '0014_auto_20160719_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor_emonth',
            name='battery',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='sensor_emonth',
            name='node_id',
            field=models.IntegerField(choices=[(5, 5), (6, 6), (7, 7), (8, 8)], default=0),
        ),
        migrations.AlterField(
            model_name='sensor_emontx',
            name='node_id',
            field=models.IntegerField(choices=[(20, 20), (21, 21), (22, 22)], default=0),
        ),
    ]
