# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-26 12:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seshdash', '0015_auto_20160722_1425'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensor_emontx',
            old_name='power1',
            new_name='index1',
        ),
        migrations.RenameField(
            model_name='sensor_emontx',
            old_name='pulse',
            new_name='index10',
        ),
        migrations.RenameField(
            model_name='sensor_emontx',
            old_name='temp1',
            new_name='index11',
        ),
        migrations.RenameField(
            model_name='sensor_emontx',
            old_name='temp2',
            new_name='index12',
        ),
        migrations.RenameField(
            model_name='sensor_emontx',
            old_name='power2',
            new_name='index2',
        ),
        migrations.RenameField(
            model_name='sensor_emontx',
            old_name='power3',
            new_name='index3',
        ),
        migrations.RenameField(
            model_name='sensor_emontx',
            old_name='power4',
            new_name='index4',
        ),
        migrations.RenameField(
            model_name='sensor_emontx',
            old_name='vrms',
            new_name='index5',
        ),
        migrations.RenameField(
            model_name='sensor_emontx',
            old_name='temp3',
            new_name='index6',
        ),
        migrations.RenameField(
            model_name='sensor_emontx',
            old_name='temp4',
            new_name='index7',
        ),
        migrations.RenameField(
            model_name='sensor_emontx',
            old_name='temp5',
            new_name='index8',
        ),
        migrations.RenameField(
            model_name='sensor_emontx',
            old_name='temp6',
            new_name='index9',
        ),
        migrations.RemoveField(
            model_name='sensor_bmv',
            name='alarm',
        ),
        migrations.RemoveField(
            model_name='sensor_bmv',
            name='ce',
        ),
        migrations.RemoveField(
            model_name='sensor_bmv',
            name='i',
        ),
        migrations.RemoveField(
            model_name='sensor_bmv',
            name='relay',
        ),
        migrations.RemoveField(
            model_name='sensor_bmv',
            name='soc',
        ),
        migrations.RemoveField(
            model_name='sensor_bmv',
            name='ttg',
        ),
        migrations.RemoveField(
            model_name='sensor_bmv',
            name='v',
        ),
        migrations.RemoveField(
            model_name='sensor_emonth',
            name='battery',
        ),
        migrations.RemoveField(
            model_name='sensor_emonth',
            name='external_temperature',
        ),
        migrations.RemoveField(
            model_name='sensor_emonth',
            name='humidity',
        ),
        migrations.RemoveField(
            model_name='sensor_emonth',
            name='temperature',
        ),
        migrations.AddField(
            model_name='sensor_bmv',
            name='index1',
            field=models.CharField(default=b'soc', max_length=40),
        ),
        migrations.AddField(
            model_name='sensor_bmv',
            name='index2',
            field=models.CharField(default=b'ce', max_length=40),
        ),
        migrations.AddField(
            model_name='sensor_bmv',
            name='index3',
            field=models.CharField(default=b'ttg', max_length=40),
        ),
        migrations.AddField(
            model_name='sensor_bmv',
            name='index4',
            field=models.CharField(default=b'v', max_length=40),
        ),
        migrations.AddField(
            model_name='sensor_bmv',
            name='index5',
            field=models.CharField(default=b'i', max_length=40),
        ),
        migrations.AddField(
            model_name='sensor_bmv',
            name='index6',
            field=models.CharField(default=b'relay', max_length=40),
        ),
        migrations.AddField(
            model_name='sensor_bmv',
            name='index7',
            field=models.CharField(default=b'alarm', max_length=40),
        ),
        migrations.AddField(
            model_name='sensor_emonth',
            name='index1',
            field=models.CharField(default=b'tempreature', max_length=40),
        ),
        migrations.AddField(
            model_name='sensor_emonth',
            name='index2',
            field=models.CharField(default=b'external_tempreature', max_length=40),
        ),
        migrations.AddField(
            model_name='sensor_emonth',
            name='index3',
            field=models.CharField(default=b'humidity', max_length=40),
        ),
        migrations.AddField(
            model_name='sensor_emonth',
            name='index4',
            field=models.CharField(default=b'battery', max_length=40),
        ),
        migrations.AlterField(
            model_name='sensor_bmv',
            name='node_id',
            field=models.IntegerField(choices=[(29, 29)], default=0),
        ),
        migrations.AlterField(
            model_name='sesh_site',
            name='site_measurements',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='seshdash.Site_Measurements'),
        ),
        migrations.AlterField(
            model_name='site_measurements',
            name='row1',
            field=models.CharField(choices=[(b'AC_Load_in', b'AC Load in'), (b'AC_Load_out', b'AC Load out'), (b'AC_Voltage_in', b'AC Voltage in'), (b'AC_Voltage_out', b'AC Voltage out'), (b'AC_input', b'AC input'), (b'AC_output', b'AC output'), (b'AC_output_absolute', b'AC output absolute'), (b'battery_voltage', b'Battery Voltage'), (b'genset_state', b'Genset state'), (b'main_on', b'Main on'), (b'pv_production', b'PV production'), (b'relay_state', b'Relay state'), (b'soc', b'State of Charge'), (b'trans', b'Trans'), (b'cloud_cover', b'Cloud Cover'), (b'daily_battery_charge', b'Daily Battery Charge'), (b'daily_grid_outage_n', b'Daily Grid Outage N'), (b'daily_grid_outage_t', b'Daily Grid Outage T'), (b'daily_grid_usage', b'Daily Grid Usage'), (b'daily_no_of_alerts', b'Daily Number of Alerts'), (b'daily_power_cons_pv', b'Daily Power Cons Pv'), (b'daily_power_consumption_total', b'Daily Power Consumption Total'), (b'daily_pv_yield', b'Daily Pv Yield')], default=b'soc', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='site_measurements',
            name='row10',
            field=models.CharField(choices=[(b'AC_Load_in', b'AC Load in'), (b'AC_Load_out', b'AC Load out'), (b'AC_Voltage_in', b'AC Voltage in'), (b'AC_Voltage_out', b'AC Voltage out'), (b'AC_input', b'AC input'), (b'AC_output', b'AC output'), (b'AC_output_absolute', b'AC output absolute'), (b'battery_voltage', b'Battery Voltage'), (b'genset_state', b'Genset state'), (b'main_on', b'Main on'), (b'pv_production', b'PV production'), (b'relay_state', b'Relay state'), (b'soc', b'State of Charge'), (b'trans', b'Trans'), (b'cloud_cover', b'Cloud Cover'), (b'daily_battery_charge', b'Daily Battery Charge'), (b'daily_grid_outage_n', b'Daily Grid Outage N'), (b'daily_grid_outage_t', b'Daily Grid Outage T'), (b'daily_grid_usage', b'Daily Grid Usage'), (b'daily_no_of_alerts', b'Daily Number of Alerts'), (b'daily_power_cons_pv', b'Daily Power Cons Pv'), (b'daily_power_consumption_total', b'Daily Power Consumption Total'), (b'daily_pv_yield', b'Daily Pv Yield')], default=b'cloud_cover', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='site_measurements',
            name='row11',
            field=models.CharField(choices=[(b'AC_Load_in', b'AC Load in'), (b'AC_Load_out', b'AC Load out'), (b'AC_Voltage_in', b'AC Voltage in'), (b'AC_Voltage_out', b'AC Voltage out'), (b'AC_input', b'AC input'), (b'AC_output', b'AC output'), (b'AC_output_absolute', b'AC output absolute'), (b'battery_voltage', b'Battery Voltage'), (b'genset_state', b'Genset state'), (b'main_on', b'Main on'), (b'pv_production', b'PV production'), (b'relay_state', b'Relay state'), (b'soc', b'State of Charge'), (b'trans', b'Trans'), (b'cloud_cover', b'Cloud Cover'), (b'daily_battery_charge', b'Daily Battery Charge'), (b'daily_grid_outage_n', b'Daily Grid Outage N'), (b'daily_grid_outage_t', b'Daily Grid Outage T'), (b'daily_grid_usage', b'Daily Grid Usage'), (b'daily_no_of_alerts', b'Daily Number of Alerts'), (b'daily_power_cons_pv', b'Daily Power Cons Pv'), (b'daily_power_consumption_total', b'Daily Power Consumption Total'), (b'daily_pv_yield', b'Daily Pv Yield')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='site_measurements',
            name='row12',
            field=models.CharField(choices=[(b'AC_Load_in', b'AC Load in'), (b'AC_Load_out', b'AC Load out'), (b'AC_Voltage_in', b'AC Voltage in'), (b'AC_Voltage_out', b'AC Voltage out'), (b'AC_input', b'AC input'), (b'AC_output', b'AC output'), (b'AC_output_absolute', b'AC output absolute'), (b'battery_voltage', b'Battery Voltage'), (b'genset_state', b'Genset state'), (b'main_on', b'Main on'), (b'pv_production', b'PV production'), (b'relay_state', b'Relay state'), (b'soc', b'State of Charge'), (b'trans', b'Trans'), (b'cloud_cover', b'Cloud Cover'), (b'daily_battery_charge', b'Daily Battery Charge'), (b'daily_grid_outage_n', b'Daily Grid Outage N'), (b'daily_grid_outage_t', b'Daily Grid Outage T'), (b'daily_grid_usage', b'Daily Grid Usage'), (b'daily_no_of_alerts', b'Daily Number of Alerts'), (b'daily_power_cons_pv', b'Daily Power Cons Pv'), (b'daily_power_consumption_total', b'Daily Power Consumption Total'), (b'daily_pv_yield', b'Daily Pv Yield')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='site_measurements',
            name='row13',
            field=models.CharField(choices=[(b'AC_Load_in', b'AC Load in'), (b'AC_Load_out', b'AC Load out'), (b'AC_Voltage_in', b'AC Voltage in'), (b'AC_Voltage_out', b'AC Voltage out'), (b'AC_input', b'AC input'), (b'AC_output', b'AC output'), (b'AC_output_absolute', b'AC output absolute'), (b'battery_voltage', b'Battery Voltage'), (b'genset_state', b'Genset state'), (b'main_on', b'Main on'), (b'pv_production', b'PV production'), (b'relay_state', b'Relay state'), (b'soc', b'State of Charge'), (b'trans', b'Trans'), (b'cloud_cover', b'Cloud Cover'), (b'daily_battery_charge', b'Daily Battery Charge'), (b'daily_grid_outage_n', b'Daily Grid Outage N'), (b'daily_grid_outage_t', b'Daily Grid Outage T'), (b'daily_grid_usage', b'Daily Grid Usage'), (b'daily_no_of_alerts', b'Daily Number of Alerts'), (b'daily_power_cons_pv', b'Daily Power Cons Pv'), (b'daily_power_consumption_total', b'Daily Power Consumption Total'), (b'daily_pv_yield', b'Daily Pv Yield')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='site_measurements',
            name='row14',
            field=models.CharField(choices=[(b'AC_Load_in', b'AC Load in'), (b'AC_Load_out', b'AC Load out'), (b'AC_Voltage_in', b'AC Voltage in'), (b'AC_Voltage_out', b'AC Voltage out'), (b'AC_input', b'AC input'), (b'AC_output', b'AC output'), (b'AC_output_absolute', b'AC output absolute'), (b'battery_voltage', b'Battery Voltage'), (b'genset_state', b'Genset state'), (b'main_on', b'Main on'), (b'pv_production', b'PV production'), (b'relay_state', b'Relay state'), (b'soc', b'State of Charge'), (b'trans', b'Trans'), (b'cloud_cover', b'Cloud Cover'), (b'daily_battery_charge', b'Daily Battery Charge'), (b'daily_grid_outage_n', b'Daily Grid Outage N'), (b'daily_grid_outage_t', b'Daily Grid Outage T'), (b'daily_grid_usage', b'Daily Grid Usage'), (b'daily_no_of_alerts', b'Daily Number of Alerts'), (b'daily_power_cons_pv', b'Daily Power Cons Pv'), (b'daily_power_consumption_total', b'Daily Power Consumption Total'), (b'daily_pv_yield', b'Daily Pv Yield')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='site_measurements',
            name='row15',
            field=models.CharField(choices=[(b'AC_Load_in', b'AC Load in'), (b'AC_Load_out', b'AC Load out'), (b'AC_Voltage_in', b'AC Voltage in'), (b'AC_Voltage_out', b'AC Voltage out'), (b'AC_input', b'AC input'), (b'AC_output', b'AC output'), (b'AC_output_absolute', b'AC output absolute'), (b'battery_voltage', b'Battery Voltage'), (b'genset_state', b'Genset state'), (b'main_on', b'Main on'), (b'pv_production', b'PV production'), (b'relay_state', b'Relay state'), (b'soc', b'State of Charge'), (b'trans', b'Trans'), (b'cloud_cover', b'Cloud Cover'), (b'daily_battery_charge', b'Daily Battery Charge'), (b'daily_grid_outage_n', b'Daily Grid Outage N'), (b'daily_grid_outage_t', b'Daily Grid Outage T'), (b'daily_grid_usage', b'Daily Grid Usage'), (b'daily_no_of_alerts', b'Daily Number of Alerts'), (b'daily_power_cons_pv', b'Daily Power Cons Pv'), (b'daily_power_consumption_total', b'Daily Power Consumption Total'), (b'daily_pv_yield', b'Daily Pv Yield')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='site_measurements',
            name='row2',
            field=models.CharField(choices=[(b'AC_Load_in', b'AC Load in'), (b'AC_Load_out', b'AC Load out'), (b'AC_Voltage_in', b'AC Voltage in'), (b'AC_Voltage_out', b'AC Voltage out'), (b'AC_input', b'AC input'), (b'AC_output', b'AC output'), (b'AC_output_absolute', b'AC output absolute'), (b'battery_voltage', b'Battery Voltage'), (b'genset_state', b'Genset state'), (b'main_on', b'Main on'), (b'pv_production', b'PV production'), (b'relay_state', b'Relay state'), (b'soc', b'State of Charge'), (b'trans', b'Trans'), (b'cloud_cover', b'Cloud Cover'), (b'daily_battery_charge', b'Daily Battery Charge'), (b'daily_grid_outage_n', b'Daily Grid Outage N'), (b'daily_grid_outage_t', b'Daily Grid Outage T'), (b'daily_grid_usage', b'Daily Grid Usage'), (b'daily_no_of_alerts', b'Daily Number of Alerts'), (b'daily_power_cons_pv', b'Daily Power Cons Pv'), (b'daily_power_consumption_total', b'Daily Power Consumption Total'), (b'daily_pv_yield', b'Daily Pv Yield')], default=b'battery_voltage', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='site_measurements',
            name='row3',
            field=models.CharField(choices=[(b'AC_Load_in', b'AC Load in'), (b'AC_Load_out', b'AC Load out'), (b'AC_Voltage_in', b'AC Voltage in'), (b'AC_Voltage_out', b'AC Voltage out'), (b'AC_input', b'AC input'), (b'AC_output', b'AC output'), (b'AC_output_absolute', b'AC output absolute'), (b'battery_voltage', b'Battery Voltage'), (b'genset_state', b'Genset state'), (b'main_on', b'Main on'), (b'pv_production', b'PV production'), (b'relay_state', b'Relay state'), (b'soc', b'State of Charge'), (b'trans', b'Trans'), (b'cloud_cover', b'Cloud Cover'), (b'daily_battery_charge', b'Daily Battery Charge'), (b'daily_grid_outage_n', b'Daily Grid Outage N'), (b'daily_grid_outage_t', b'Daily Grid Outage T'), (b'daily_grid_usage', b'Daily Grid Usage'), (b'daily_no_of_alerts', b'Daily Number of Alerts'), (b'daily_power_cons_pv', b'Daily Power Cons Pv'), (b'daily_power_consumption_total', b'Daily Power Consumption Total'), (b'daily_pv_yield', b'Daily Pv Yield')], default=b'AC_output_absolute', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='site_measurements',
            name='row4',
            field=models.CharField(choices=[(b'AC_Load_in', b'AC Load in'), (b'AC_Load_out', b'AC Load out'), (b'AC_Voltage_in', b'AC Voltage in'), (b'AC_Voltage_out', b'AC Voltage out'), (b'AC_input', b'AC input'), (b'AC_output', b'AC output'), (b'AC_output_absolute', b'AC output absolute'), (b'battery_voltage', b'Battery Voltage'), (b'genset_state', b'Genset state'), (b'main_on', b'Main on'), (b'pv_production', b'PV production'), (b'relay_state', b'Relay state'), (b'soc', b'State of Charge'), (b'trans', b'Trans'), (b'cloud_cover', b'Cloud Cover'), (b'daily_battery_charge', b'Daily Battery Charge'), (b'daily_grid_outage_n', b'Daily Grid Outage N'), (b'daily_grid_outage_t', b'Daily Grid Outage T'), (b'daily_grid_usage', b'Daily Grid Usage'), (b'daily_no_of_alerts', b'Daily Number of Alerts'), (b'daily_power_cons_pv', b'Daily Power Cons Pv'), (b'daily_power_consumption_total', b'Daily Power Consumption Total'), (b'daily_pv_yield', b'Daily Pv Yield')], default=b'AC_Load_in', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='site_measurements',
            name='row5',
            field=models.CharField(choices=[(b'AC_Load_in', b'AC Load in'), (b'AC_Load_out', b'AC Load out'), (b'AC_Voltage_in', b'AC Voltage in'), (b'AC_Voltage_out', b'AC Voltage out'), (b'AC_input', b'AC input'), (b'AC_output', b'AC output'), (b'AC_output_absolute', b'AC output absolute'), (b'battery_voltage', b'Battery Voltage'), (b'genset_state', b'Genset state'), (b'main_on', b'Main on'), (b'pv_production', b'PV production'), (b'relay_state', b'Relay state'), (b'soc', b'State of Charge'), (b'trans', b'Trans'), (b'cloud_cover', b'Cloud Cover'), (b'daily_battery_charge', b'Daily Battery Charge'), (b'daily_grid_outage_n', b'Daily Grid Outage N'), (b'daily_grid_outage_t', b'Daily Grid Outage T'), (b'daily_grid_usage', b'Daily Grid Usage'), (b'daily_no_of_alerts', b'Daily Number of Alerts'), (b'daily_power_cons_pv', b'Daily Power Cons Pv'), (b'daily_power_consumption_total', b'Daily Power Consumption Total'), (b'daily_pv_yield', b'Daily Pv Yield')], default=b'AC_Load_out', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='site_measurements',
            name='row6',
            field=models.CharField(choices=[(b'AC_Load_in', b'AC Load in'), (b'AC_Load_out', b'AC Load out'), (b'AC_Voltage_in', b'AC Voltage in'), (b'AC_Voltage_out', b'AC Voltage out'), (b'AC_input', b'AC input'), (b'AC_output', b'AC output'), (b'AC_output_absolute', b'AC output absolute'), (b'battery_voltage', b'Battery Voltage'), (b'genset_state', b'Genset state'), (b'main_on', b'Main on'), (b'pv_production', b'PV production'), (b'relay_state', b'Relay state'), (b'soc', b'State of Charge'), (b'trans', b'Trans'), (b'cloud_cover', b'Cloud Cover'), (b'daily_battery_charge', b'Daily Battery Charge'), (b'daily_grid_outage_n', b'Daily Grid Outage N'), (b'daily_grid_outage_t', b'Daily Grid Outage T'), (b'daily_grid_usage', b'Daily Grid Usage'), (b'daily_no_of_alerts', b'Daily Number of Alerts'), (b'daily_power_cons_pv', b'Daily Power Cons Pv'), (b'daily_power_consumption_total', b'Daily Power Consumption Total'), (b'daily_pv_yield', b'Daily Pv Yield')], default=b'AC_Voltage_in', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='site_measurements',
            name='row7',
            field=models.CharField(choices=[(b'AC_Load_in', b'AC Load in'), (b'AC_Load_out', b'AC Load out'), (b'AC_Voltage_in', b'AC Voltage in'), (b'AC_Voltage_out', b'AC Voltage out'), (b'AC_input', b'AC input'), (b'AC_output', b'AC output'), (b'AC_output_absolute', b'AC output absolute'), (b'battery_voltage', b'Battery Voltage'), (b'genset_state', b'Genset state'), (b'main_on', b'Main on'), (b'pv_production', b'PV production'), (b'relay_state', b'Relay state'), (b'soc', b'State of Charge'), (b'trans', b'Trans'), (b'cloud_cover', b'Cloud Cover'), (b'daily_battery_charge', b'Daily Battery Charge'), (b'daily_grid_outage_n', b'Daily Grid Outage N'), (b'daily_grid_outage_t', b'Daily Grid Outage T'), (b'daily_grid_usage', b'Daily Grid Usage'), (b'daily_no_of_alerts', b'Daily Number of Alerts'), (b'daily_power_cons_pv', b'Daily Power Cons Pv'), (b'daily_power_consumption_total', b'Daily Power Consumption Total'), (b'daily_pv_yield', b'Daily Pv Yield')], default=b'AC_Voltage_out', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='site_measurements',
            name='row8',
            field=models.CharField(choices=[(b'AC_Load_in', b'AC Load in'), (b'AC_Load_out', b'AC Load out'), (b'AC_Voltage_in', b'AC Voltage in'), (b'AC_Voltage_out', b'AC Voltage out'), (b'AC_input', b'AC input'), (b'AC_output', b'AC output'), (b'AC_output_absolute', b'AC output absolute'), (b'battery_voltage', b'Battery Voltage'), (b'genset_state', b'Genset state'), (b'main_on', b'Main on'), (b'pv_production', b'PV production'), (b'relay_state', b'Relay state'), (b'soc', b'State of Charge'), (b'trans', b'Trans'), (b'cloud_cover', b'Cloud Cover'), (b'daily_battery_charge', b'Daily Battery Charge'), (b'daily_grid_outage_n', b'Daily Grid Outage N'), (b'daily_grid_outage_t', b'Daily Grid Outage T'), (b'daily_grid_usage', b'Daily Grid Usage'), (b'daily_no_of_alerts', b'Daily Number of Alerts'), (b'daily_power_cons_pv', b'Daily Power Cons Pv'), (b'daily_power_consumption_total', b'Daily Power Consumption Total'), (b'daily_pv_yield', b'Daily Pv Yield')], default=b'AC_input', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='site_measurements',
            name='row9',
            field=models.CharField(choices=[(b'AC_Load_in', b'AC Load in'), (b'AC_Load_out', b'AC Load out'), (b'AC_Voltage_in', b'AC Voltage in'), (b'AC_Voltage_out', b'AC Voltage out'), (b'AC_input', b'AC input'), (b'AC_output', b'AC output'), (b'AC_output_absolute', b'AC output absolute'), (b'battery_voltage', b'Battery Voltage'), (b'genset_state', b'Genset state'), (b'main_on', b'Main on'), (b'pv_production', b'PV production'), (b'relay_state', b'Relay state'), (b'soc', b'State of Charge'), (b'trans', b'Trans'), (b'cloud_cover', b'Cloud Cover'), (b'daily_battery_charge', b'Daily Battery Charge'), (b'daily_grid_outage_n', b'Daily Grid Outage N'), (b'daily_grid_outage_t', b'Daily Grid Outage T'), (b'daily_grid_usage', b'Daily Grid Usage'), (b'daily_no_of_alerts', b'Daily Number of Alerts'), (b'daily_power_cons_pv', b'Daily Power Cons Pv'), (b'daily_power_consumption_total', b'Daily Power Consumption Total'), (b'daily_pv_yield', b'Daily Pv Yield')], default=b'AC_output', max_length=30, null=True),
        ),
    ]
