# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-11 10:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seshdash', '0016_sesh_alert_trigger_alert'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sesh_alert',
            old_name='trigger_alert',
            new_name='point',
        ),
    ]
