# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-17 12:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seshdash', '0017_sensor_mapping'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sensor_mapping',
            unique_together=set([('site_id', 'node_id', 'sensor_type')]),
        ),
    ]
