# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-16 14:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seshdash', '0017_auto_20160311_1228'),
    ]

    operations = [
        migrations.CreateModel(
            name='RMC_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(default=None)),
                ('last_contact', models.DateTimeField(default=None)),
                ('signal_strength', models.IntegerField(default=None)),
                ('data_sent_24h', models.IntegerField(default=None)),
                ('rmc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seshdash.SESH_RMC_Account')),
            ],
        ),
        migrations.AddField(
            model_name='sesh_site',
            name='rmc_account',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='seshdash.SESH_RMC_Account'),
        ),
        migrations.AlterField(
            model_name='sesh_site',
            name='vrm_account',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='seshdash.VRM_Account'),
        ),
    ]
