# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-22 12:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def emonpis_for_sites(apps, schema_editor):
    """
    This will create emonpis for sites that
    are already existing in the database
    """
    print "About to generate the emopis for each site"
    Sesh_Site = apps.get_model('seshdash', 'Sesh_Site')
    sites = Sesh_Site.objects.all()
    print "The sites are: %s" % (sites)
    EmonPi = apps.get_model('seshdash', 'EmonPi')

    for site in sites:
        site.emonpi = EmonPi.objects.create()
        site.save()
        print site.emonpi

def reverse_emonpis_for_sites(apps, schema_editor):
    """
    Function to reverse the operations done in
    function emonpis_for_sites
    """
    Sesh_Site = apps.get_model('seshdash', 'Sesh_Site')
    sites = Sesh_Site.objects.all()

    for site in sites:
        if hasattr(site, 'emonpi'):
            del(site.emonpi)

class Migration(migrations.Migration):

    dependencies = [
        ('seshdash', '0019_auto_20160822_1123'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmonPi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.IntegerField(default=5, editable=False)),
                ('index1', models.CharField(default=b'power1', max_length=40)),
                ('index2', models.CharField(default=b'power2', max_length=40)),
                ('index3', models.CharField(default=b'power3', max_length=40)),
                ('index4', models.CharField(default=b'power4', max_length=40)),
                ('index5', models.CharField(default=b'v_battery_bank', max_length=40)),
                ('index6', models.CharField(default=b'Vrms', max_length=40)),
                ('index7', models.CharField(default=b'T1', max_length=40)),
                ('index8', models.CharField(default=b'T2', max_length=40)),
                ('index9', models.CharField(default=b'T3', max_length=40)),
                ('index10', models.CharField(default=b'T4', max_length=40)),
                ('index11', models.CharField(default=b'T5', max_length=40)),
                ('index12', models.CharField(default=b'T6', max_length=40)),
                ('index13', models.CharField(default=b'pulseCount', max_length=40)),
            ],
        ),
        migrations.AlterField(
            model_name='sensor_emonth',
            name='node_id',
            field=models.IntegerField(choices=[(6, 6), (7, 7), (8, 8)], default=0),
        ),
        migrations.AddField(
            model_name='sesh_site',
            name='emonpi',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='seshdash.EmonPi'),
            preserve_default=False,
        ),
        migrations.RunPython(emonpis_for_sites, reverse_emonpis_for_sites),
    ]
