# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-17 13:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seshdash', '0019_auto_20160317_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sesh_rmc_account',
            name='site',
        ),
        migrations.AddField(
            model_name='sesh_site',
            name='rmc_account',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='seshdash.SESH_RMC_Account'),
        ),
    ]
