# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-22 14:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seshdash', '0020_auto_20160822_1423'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmonPi',
            new_name='Sensor_EmonPi',
        ),
        
    ]
