# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-21 07:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seshdash', '0021_auto_20160320_1858'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sesh_site',
            options={},
        ),
        migrations.RemoveField(
            model_name='sesh_site',
            name='rmc_account',
        ),
        migrations.AddField(
            model_name='sesh_rmc_account',
            name='rmc_account',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='seshdash.Sesh_Site'),
        ),
        migrations.AlterField(
            model_name='sesh_rmc_account',
            name='API_KEY',
            field=models.CharField(default=b'', max_length=130),
        ),
    ]
