# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-25 10:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def delete_one_to_one_emonpis(apps, schema_editor):
    """
    To delete the one to one emonpi sensors already
    exisiting in the database
    """
    Sesh_Site = apps.get_model('seshdash', 'Sesh_Site')
    sites = Sesh_Site.objects.all()

    for site in sites:
        if hasattr(site, 'emonpi') and (getattr(site, 'emonpi') is not None):
            site.emonpi.delete()


def add_one_to_one_emonpis(apps, schema_editor):
    """
    To add one to one emonpis to each site
    """
    Sesh_Site = apps.get_model('seshdash', 'Sesh_Site')
    Sensor_EmonPi = apps.get_model('seshdash', 'Sensor_EmonPi')
    sites = Sesh_Site.objects.all()

    for site in sites:
        site.emonpi = Sensor_EmonPi.objects.create()
        site.save()


def add_emonpis_for_site(apps, schema_editor):
    """
    Changing the emonpis to reference using foreignkeys
    rather than one to one relation ships
    """
    Sesh_Site = apps.get_model('seshdash', 'Sesh_Site')
    Sensor_EmonPi = apps.get_model('seshdash', 'Sensor_EmonPi')
    sites = Sesh_Site.objects.all()

    for site in sites:
        Sensor_EmonPi.objects.create(site=site)

def delete_emonpis_for_site(apps, schema_editor):
    """
    Reversing the actions done by function emonpis for site
    """

    Sesh_Site = apps.get_model('seshdash', 'Sesh_Site')
    Sensor_EmonPi = apps.get_model('seshdash', 'Sensor_EmonPi')
    sites = Sesh_Site.objects.all()

    for site in sites:
        site.sensor_emonpi_set.all().delete()
        site.save()



class Migration(migrations.Migration):

    dependencies = [
        ('seshdash', '0021_auto_20160822_1622'),
    ]

    operations = [

        migrations.RunPython(delete_one_to_one_emonpis, add_one_to_one_emonpis),

        migrations.RemoveField(
            model_name='sesh_site',
            name='emonpi',
        ),


        migrations.AddField(
            model_name='sensor_emonpi',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='seshdash.Sesh_Site'),
            preserve_default=False,
        ),

        migrations.RunPython(add_emonpis_for_site, delete_emonpis_for_site),


        migrations.AlterField(
            model_name='sesh_rmc_account',
            name='api_key',
            field=models.CharField(default=b'', max_length=130, unique=True),
        ),
        migrations.AlterField(
            model_name='sesh_rmc_account',
            name='api_key_numeric',
            field=models.CharField(default=b'', max_length=130, unique=True),
        ),
    ]
