# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-21 11:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seshdash', '0022_auto_20160321_0926'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sesh_site',
            options={'permissions': (('view_Sesh_Site', 'View Sesh Site'),), 'verbose_name': 'Sesh Site', 'verbose_name_plural': 'Sesh Sites'},
        ),
        migrations.RenameField(
            model_name='sesh_site',
            old_name='number_of_pv_strings',
            new_name='system_voltage',
        ),
        migrations.RemoveField(
            model_name='sesh_rmc_account',
            name='rmc_account',
        ),
        migrations.AddField(
            model_name='sesh_site',
            name='rmc_account',
            field=models.ForeignKey(blank=True, default=b'', max_length=20, null=True, on_delete=django.db.models.deletion.CASCADE, to='seshdash.Sesh_RMC_Account'),
        ),
        migrations.AlterField(
            model_name='rmc_status',
            name='rmc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seshdash.Sesh_RMC_Account'),
        ),
    ]
