# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-20 12:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        ('seshdash', '0023_auto_20160920_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sesh_organisation',
            name='group',
        ),
        migrations.RemoveField(
            model_name='sesh_organisation',
            name='id',
        ),
        migrations.AddField(
            model_name='sesh_organisation',
            name='group_ptr',
            field=models.OneToOneField(auto_created=True, default='', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.Group'),
            preserve_default=False,
        ),
    ]
