# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-04 07:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seshdash', '0023_auto_20160321_1350'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sesh_rmc_account',
            options={'verbose_name': 'RMC API Account'},
        ),
        migrations.RenameField(
            model_name='sesh_site',
            old_name='Number_of_panels',
            new_name='number_of_panels',
        ),
        migrations.AddField(
            model_name='sesh_site',
            name='updating',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rmc_status',
            name='rmc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seshdash.Sesh_RMC_Account'),
        ),
        migrations.AlterField(
            model_name='sesh_site',
            name='rmc_account',
            field=models.ForeignKey(blank=True, default=b'', max_length=20, null=True, on_delete=django.db.models.deletion.CASCADE, to='seshdash.Sesh_RMC_Account'),
        ),
    ]
