# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-22 13:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        ('seshdash', '0024_auto_20160920_1409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sesh_organisation',
            name='group_ptr',
        ),
        migrations.AddField(
            model_name='sesh_organisation',
            name='group',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sesh_organisation',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
