# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-27 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seshdash', '0025_auto_20160922_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sesh_organisation',
            name='group',
        ),
        migrations.AddField(
            model_name='sesh_organisation',
            name='name',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
    ]
