# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-28 12:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seshdash', '0026_auto_20160328_1334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sesh_site',
            name='on_call_user',
        ),
        migrations.AddField(
            model_name='alert_rule',
            name='send_sms',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sesh_user',
            name='on_call',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rmc_status',
            name='rmc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seshdash.Sesh_RMC_Account'),
        ),
        migrations.AlterField(
            model_name='sesh_site',
            name='rmc_account',
            field=models.ForeignKey(blank=True, default=b'', max_length=20, null=True, on_delete=django.db.models.deletion.CASCADE, to='seshdash.Sesh_RMC_Account'),
        ),
    ]
