# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-27 13:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seshdash', '0026_auto_20160927_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesh_user',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seshdash.Sesh_Organisation'),
            preserve_default=False,
        ),
    ]
