# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-29 12:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seshdash', '0028_auto_20160328_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert_rule',
            name='check_field',
            field=models.CharField(choices=[(b'battery_voltage', b'battery voltage'), (b'soc', b'System State of Charge'), (b'AC_output', b'AC Loads'), (b'pv_production', b'Solar Energy Produced'), (b'main_on', b'Grid Availible'), (b'genset_state', b'Generator on'), (b'model#field_name', b'Model FieldName'), (b'RMC_status#last_contact', b'RMC Last Contact')], max_length=100),
        ),
        migrations.AlterField(
            model_name='rmc_status',
            name='rmc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seshdash.Sesh_RMC_Account'),
        ),
        migrations.AlterField(
            model_name='sesh_site',
            name='rmc_account',
            field=models.ForeignKey(blank=True, default=b'', max_length=20, null=True, on_delete=django.db.models.deletion.CASCADE, to='seshdash.Sesh_RMC_Account'),
        ),
    ]
