# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-27 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seshdash', '0028_auto_20160927_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesh_user',
            name='is_org_admin',
            field=models.BooleanField(default=False),
        ),
    ]
