# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-27 13:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seshdash', '0029_sesh_user_is_org_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesh_site',
            name='organisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='seshdash.Sesh_Organisation'),
        ),
    ]
