# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-11 11:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seshdash', '0030_sesh_site_organisation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesh_site',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seshdash.Sesh_Organisation'),
        ),
    ]
