# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-29 13:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seshdash', '0030_auto_20160329_1445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rmc_status',
            name='last_contact',
        ),
        migrations.AddField(
            model_name='rmc_status',
            name='minutes_last_contact',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='rmc_status',
            name='rmc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seshdash.Sesh_RMC_Account'),
        ),
        migrations.AlterField(
            model_name='sesh_site',
            name='rmc_account',
            field=models.ForeignKey(blank=True, default=b'', max_length=20, null=True, on_delete=django.db.models.deletion.CASCADE, to='seshdash.Sesh_RMC_Account'),
        ),
    ]
