# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-31 11:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('seshdash', '0033_auto_20160331_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sesh_alert',
            name='point',
        ),
        migrations.AddField(
            model_name='rmc_status',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 31, 11, 24, 49, 869894, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sesh_alert',
            name='model_point_name',
            field=models.CharField(default=b'BoM_Data_Point', max_length=30),
        ),
        migrations.AlterField(
            model_name='alert_rule',
            name='check_field',
            field=models.CharField(choices=[(b'BoM_Data_Point#battery_voltage', b'battery voltage'), (b'BoM_Data_Point#soc', b'System State of Charge'), (b'BoM_Data_Point#AC_output', b'AC Loads'), (b'BoM_Data_Point#pv_production', b'Solar Energy Produced'), (b'BoM_Data_Point#main_on', b'Grid Availible'), (b'BoM_Data_Point#genset_state', b'Generator on'), (b'RMC_status#minutes_last_contact', b'RMC Last Contact')], max_length=100),
        ),
        migrations.AlterField(
            model_name='rmc_status',
            name='rmc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seshdash.Sesh_RMC_Account'),
        ),
        migrations.AlterField(
            model_name='sesh_site',
            name='rmc_account',
            field=models.ForeignKey(blank=True, default=b'', max_length=20, null=True, on_delete=django.db.models.deletion.CASCADE, to='seshdash.Sesh_RMC_Account'),
        ),
    ]
