# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-11 11:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seshdash', '0028_auto_20160411_1055'),
        ('seshdash', '0044_auto_20160404_1457'),
    ]

    operations = [
    ]
