# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-18 14:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seshdash', '0052_auto_20160418_1339'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rmc_status',
            options={'verbose_name': 'System Alert', 'verbose_name_plural': 'System Alerts'},
        ),
        migrations.AlterModelOptions(
            name='sesh_alert',
            options={'verbose_name': 'System Alert', 'verbose_name_plural': 'System Alerts'},
        ),
        migrations.AddField(
            model_name='rmc_status',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seshdash.Sesh_Site'),
        ),
        migrations.AlterField(
            model_name='rmc_status',
            name='rmc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seshdash.Sesh_RMC_Account'),
        ),
        migrations.AlterField(
            model_name='sesh_site',
            name='rmc_account',
            field=models.ForeignKey(blank=True, default=b'', max_length=20, null=True, on_delete=django.db.models.deletion.CASCADE, to='seshdash.Sesh_RMC_Account'),
        ),
    ]
