# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-18 14:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seshdash', '0053_auto_20160418_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rmc_status',
            name='data_sent_24h',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='rmc_status',
            name='ip_address',
            field=models.GenericIPAddressField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='rmc_status',
            name='rmc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seshdash.Sesh_RMC_Account'),
        ),
        migrations.AlterField(
            model_name='rmc_status',
            name='signal_strength',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='sesh_site',
            name='rmc_account',
            field=models.ForeignKey(blank=True, default=b'', max_length=20, null=True, on_delete=django.db.models.deletion.CASCADE, to='seshdash.Sesh_RMC_Account'),
        ),
    ]
