# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-21 08:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seshdash', '0046_auto_20160421_0916'),
        ('seshdash', '0054_auto_20160418_1656'),
    ]

    operations = [
    ]
