# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-21 07:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seshdash', '0053_auto_20160419_1334'),
        ('seshdash', '0054_auto_20160418_1656'),
    ]

    operations = [
    ]
