# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-22 10:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seshdash', '0058_auto_20160421_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_data_point',
            name='daily_battery_charge',
            field=models.FloatField(default=0, verbose_name=b'Battery Charge'),
        ),
        migrations.AlterField(
            model_name='daily_data_point',
            name='daily_grid_outage_n',
            field=models.FloatField(default=0, verbose_name=b'Grid outagen n'),
        ),
        migrations.AlterField(
            model_name='daily_data_point',
            name='daily_grid_outage_t',
            field=models.FloatField(default=0, verbose_name=b'Grid outage t'),
        ),
        migrations.AlterField(
            model_name='daily_data_point',
            name='daily_grid_usage',
            field=models.FloatField(default=0, verbose_name=b'Grid usage'),
        ),
        migrations.AlterField(
            model_name='daily_data_point',
            name='daily_no_of_alerts',
            field=models.IntegerField(default=0, verbose_name=b'Number of alerts'),
        ),
        migrations.AlterField(
            model_name='daily_data_point',
            name='daily_power_cons_pv',
            field=models.FloatField(default=0, verbose_name=b'Power consumption pv'),
        ),
        migrations.AlterField(
            model_name='daily_data_point',
            name='daily_power_consumption_total',
            field=models.FloatField(default=0, verbose_name=b'Daily Power Consumption'),
        ),
        migrations.AlterField(
            model_name='daily_data_point',
            name='daily_pv_yield',
            field=models.FloatField(default=0, verbose_name=b'Battery Voltage'),
        ),
        migrations.AlterField(
            model_name='rmc_status',
            name='rmc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seshdash.Sesh_RMC_Account'),
        ),
        migrations.AlterField(
            model_name='sesh_site',
            name='rmc_account',
            field=models.ForeignKey(blank=True, default=b'', max_length=20, null=True, on_delete=django.db.models.deletion.CASCADE, to='seshdash.Sesh_RMC_Account'),
        ),
    ]
