# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-22 16:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seshdash', '0052_auto_20160415_1110'),
        ('seshdash', '0059_auto_20160422_1202'),
    ]

    operations = [
    ]
