# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-26 09:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seshdash', '0062_auto_20160422_1841'),
        ('seshdash', '0062_auto_20160426_1118'),
    ]

    operations = [
    ]
