# -*- coding: utf-8 -*-
<<<<<<< HEAD
# Generated by Django 1.9.1 on 2016-05-03 07:44
=======
# Generated by Django 1.9.1 on 2016-05-03 09:59
>>>>>>> 6e138745ed003547acf1046646436af31c18d6ef
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
        ('seshdash', '0064_auto_20160430_1744'),
=======
        ('seshdash', '0063_auto_20160428_1053'),
>>>>>>> 6e138745ed003547acf1046646436af31c18d6ef
        ('seshdash', '0065_auto_20160426_1159'),
    ]

    operations = [
    ]
