# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-03 07:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seshdash', '0064_auto_20160430_1744'),
        ('seshdash', '0065_auto_20160426_1159'),
    ]

    operations = [
    ]
