# -*- coding: utf-8 -*-

# Generated by Django 1.9.1 on 2016-05-03 09:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seshdash', '0063_auto_20160428_1053'),
        ('seshdash', '0065_auto_20160426_1159'),
    ]

    operations = [
    ]
