# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-04 10:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seshdash', '0066_merge'),
        ('seshdash', '0063_auto_20160425_1457'),
    ]

    operations = [
    ]
