# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-04 09:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seshdash', '0067_auto_20160504_1004'),
        ('seshdash', '0064_auto_20160430_1744'),
    ]

    operations = [
    ]
