# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-05 09:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seshdash', '0066_merge'),
        ('seshdash', '0068_auto_20160505_1156'),
    ]

    operations = [
    ]
