# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-06 08:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seshdash', '0068_merge'),
        ('seshdash', '0068_auto_20160504_1247'),
    ]

    operations = [
    ]
