# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-09 11:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seshdash', '0067_auto_20160504_1326'),
        ('seshdash', '0070_auto_20160505_1159'),
    ]

    operations = [
    ]
