# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-10 13:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seshdash', '0072_auto_20160510_1318'),
        ('seshdash', '0073_auto_20160509_1743'),
    ]

    operations = [
    ]
