# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-13 13:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seshdash', '0075_auto_20160513_1330'),
        ('seshdash', '0075_auto_20160513_1308'),
    ]

    operations = [
    ]
