# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-20 11:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seshdash', '0082_auto_20160516_1605'),
        ('seshdash', '0075_auto_20160518_0931'),
    ]

    operations = [
    ]
