# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-23 09:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seshdash', '0083_auto_20160523_1100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sesh_user',
            name='send_slack',
        ),
        migrations.AddField(
            model_name='sesh_organisation',
            name='send_slack',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rmc_status',
            name='rmc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seshdash.Sesh_RMC_Account'),
        ),
        migrations.AlterField(
            model_name='sesh_site',
            name='rmc_account',
            field=models.ForeignKey(blank=True, default=b'', max_length=20, null=True, on_delete=django.db.models.deletion.CASCADE, to='seshdash.Sesh_RMC_Account'),
        ),
    ]
