# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-24 07:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seshdash', '0084_auto_20160523_1114'),
        ('seshdash', '0083_merge'),
    ]

    operations = [
    ]
