# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-28 15:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seshdash', '0085_merge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sesh_rmc_account',
            name='id',
        ),
        migrations.RemoveField(
            model_name='sesh_site',
            name='rmc_account',
        ),
        migrations.AddField(
            model_name='sesh_rmc_account',
            name='site',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='seshdash.Sesh_Site'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rmc_status',
            name='rmc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seshdash.Sesh_RMC_Account'),
        ),
    ]
