# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-01 09:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seshdash', '0086_auto_20160528_1712'),
        ('seshdash', '0091_auto_20160601_1044'),
    ]

    operations = [
    ]
