# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-01 13:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seshdash', '0092_merge'),
        ('seshdash', '0090_auto_20160601_1518'),
    ]

    operations = [
    ]
